<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%204.%20%D0%9E%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%20DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---4. ОБЪЕКТ DataFrame---"""

"""---4.1 ОБЗОР DataFrame---"""

"""---4.1.1 Создание объекта DataFrame на основе ассоциативного массива---"""

In [106]:
import pandas as pd
import numpy as np

In [107]:
city_data = {
    "City": ["New York", "Paris", "Barcelona", "Rome"],
    "Country": ["United States", "France", "Spain", "Italy"],
    "Population": [8600000, 2141000, 5515000, 2873000]
}

cities = pd.DataFrame(city_data)
cities

        City        Country  Population
0   New York  United States     8600000
1      Paris         France     2141000
2  Barcelona          Spain     5515000
3       Rome          Italy     2873000

In [108]:
cities.T # транспонировали таблицу

                        0        1          2        3
City             New York    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

"""---4.1.2 Создание объекта DataFrame на основе ndarray библиотеки NumPy---"""

In [109]:
random_data = np.random.randint(1, 101, [3, 5])
random_data

array([[56, 27, 55, 90, 69],
       [89, 34,  2, 69, 40],
       [65, 82, 98, 80, 85]])

In [110]:
pd.DataFrame(data=random_data)

    0   1   2   3   4
0  56  27  55  90  69
1  89  34   2  69  40
2  65  82  98  80  85

In [111]:
row_labels = ["Morning", "Afternoon", "Evening"]
temperatures = pd.DataFrame(random_data,
                            index=row_labels)
temperatures

            0   1   2   3   4
Morning    56  27  55  90  69
Afternoon  89  34   2  69  40
Evening    65  82  98  80  85

In [112]:
row_labels = ["Morning", "Afternoon", "Evening"]
column_labels = (
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday"
)
temperatures = pd.DataFrame(random_data,
                            index=row_labels,
                            columns=column_labels)
temperatures

           Monday  Tuesday  Wednesday  Thursday  Friday
Morning        56       27         55        90      69
Afternoon      89       34          2        69      40
Evening        65       82         98        80      85

In [113]:
row_labels = ["Morning", "Afternoon", "Morning"]
column_labels = (
    "Monday",
    "Tuesday",
    "Wednesday",
    "Tuesday",
    "Friday"
)
temperatures = pd.DataFrame(random_data,
                            index=row_labels,
                            columns=column_labels)
temperatures

           Monday  Tuesday  Wednesday  Tuesday  Friday
Morning        56       27         55       90      69
Afternoon      89       34          2       69      40
Morning        65       82         98       80      85

"""---4.2 ОБЩИЕ ЧЕРТЫ SERIES И DataFrame---"""

"""---4.2.1 Импорт объекта DateFrame с помощью функции read_csv---"""

In [114]:
nba = pd.read_csv("nba.csv",
            parse_dates=["Birthday"])

nba

/tmp/ipykernel_5458/2611377350.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("nba.csv",

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

"""---4.2.2 Атрибуты Series и DataFrame: сходство и различие---"""

In [115]:
pd.Series([1, 2, 3]).dtype

dtype('int64')

In [116]:
nba.dtypes

Name                object
Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [117]:
nba.dtypes.value_counts()

object            3
datetime64[ns]    1
int64             1
Name: count, dtype: int64

In [118]:
nba.index

RangeIndex(start=0, stop=450, step=1)

In [119]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [120]:
nba.ndim

2

In [121]:
nba.shape

(450, 5)

In [122]:
nba.size

2250

In [123]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [124]:
nba.count().sum()

np.int64(2250)

In [125]:
data = {
    "A": [1, np.nan],
    "B": [2, 3]
}

df = pd.DataFrame(data)

df

     A  B
0  1.0  2
1  NaN  3

In [126]:
df.size

4

In [127]:
df.count()

A    1
B    2
dtype: int64

In [128]:
df.count().sum()

np.int64(3)

"""---4.2.3 Общие методы Series и  DataFrame---"""

In [129]:
nba.head(2)

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [130]:
nba.tail(3)

              Name                 Team Position   Birthday    Salary
447    Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448  Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449    Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

In [131]:
nba.sample(3) # случайное извлечние заданного количества строк

               Name                   Team Position   Birthday    Salary
282  Andre Roberson  Oklahoma City Thunder       SF 1991-12-04  10740740
322    Josh Magette          Orlando Magic       PG 1989-11-28     79568
210    Luke Kennard        Detroit Pistons       SG 1996-06-24   3827160

In [132]:
nba.nunique() # количество уникальных значений в каждом из столбцов датафрейма

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [133]:
nba.max()

Name             Zylan Cheatham
Team         Washington Wizards
Position                     SG
Birthday    2000-12-23 00:00:00
Salary                 40231758
dtype: object

In [134]:
nba.min()

Name               Aaron Gordon
Team              Atlanta Hawks
Position                      C
Birthday    1977-01-26 00:00:00
Salary                    79568
dtype: object

In [135]:
nba.nlargest(n=4, columns="Salary") # извлекаем максимальное значение по столбцу из набора данных в заданном количестве

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000

In [136]:
nba.nsmallest(n=3, columns="Birthday") # извлекаем минимальное значение по столбцу из набора данных в заданном количестве

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

In [137]:
nba["Salary"].sum()

np.int64(3444112694)

In [138]:
nba.sum(numeric_only=True)

Salary    3444112694
dtype: int64

In [139]:
nba.mean(numeric_only=True)

Salary    7.653584e+06
dtype: float64

In [140]:
nba.median(numeric_only=True)

Salary    3303074.5
dtype: float64

In [141]:
nba.mode(numeric_only=True)

   Salary
0   79568

In [142]:
nba.std(numeric_only=True)

Salary    9.288810e+06
dtype: float64

"""---4.3 СОРТИРОВКА ОБЪЕКТА DatFrame---"""

"""---4.3.1 Сортировка по одному столбцу---"""

In [143]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [144]:
nba.sort_values("Name")

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [145]:
nba.sort_values("Name", ascending=False).head()

                Name                  Team Position   Birthday    Salary
248   Zylan Cheatham  New Orleans Pelicans       SF 1995-11-17     79568
137  Zion Williamson  New Orleans Pelicans        F 2000-07-06   9757440
312     Zhaire Smith    Philadelphia 76ers       SG 1999-06-04   3058800
302     Zach Norvell    Los Angeles Lakers       SG 1997-12-09     79568
159      Zach LaVine         Chicago Bulls       PG 1995-03-10  19500000

In [146]:
nba.sort_values("Birthday", ascending=False).head() # аналог метода nsmallest

                    Name                  Team Position   Birthday   Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23  3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25   898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06  9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14  7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13   898310

In [147]:
nba.nlargest(n=5, columns="Birthday")

                    Name                  Team Position   Birthday   Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23  3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25   898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06  9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14  7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13   898310

"""---4.3.2 Сортировка по нескольким столбцу---"""

In [148]:
nba.sort_values(["Team", "Name"])

                Name                Team Position   Birthday    Salary
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
..               ...                 ...      ...        ...       ...
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000

[450 rows x 5 columns]

In [149]:
nba.sort_values(["Team", "Name"], ascending=False)

                Name                Team Position   Birthday    Salary
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
..               ...                 ...      ...        ...       ...
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000

[450 rows x 5 columns]

In [150]:
nba.sort_values(
    ["Team", "Salary"],
    ascending=[True, False]) # сортируем в разном порядке. Столбец Team по возрастанию, столбец Salary по убыванию

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

In [151]:
nba = nba.sort_values(
    ["Team", "Salary"],
    ascending=[True, False])

nba

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

"""---4.4 СОРТИРОВКА ПО ИНДЕКСУ---"""

In [152]:
nba.head()

                 Name           Team Position   Birthday    Salary
111  Chandler Parsons  Atlanta Hawks       SF 1988-10-25  25102512
28        Evan Turner  Atlanta Hawks       PG 1988-10-27  18606556
167      Allen Crabbe  Atlanta Hawks       SG 1992-04-09  18500000
213   De'Andre Hunter  Atlanta Hawks       SF 1997-12-02   7068360
339     Jabari Parker  Atlanta Hawks       PF 1995-03-15   6500000

"""---4.4.1 Сортировка по индексу строк---"""

In [153]:
nba.sort_index().head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [154]:
nba.sort_index(ascending=False).head()

              Name                 Team Position   Birthday    Salary
449    Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000
448  Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
447    Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
446    Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
445  Austin Rivers      Houston Rockets       PG 1992-08-01   2174310

In [155]:
nba = nba.sort_index()
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

"""---4.4.2 Сортировка по индексу столбцов---"""

In [156]:
nba.sort_index(axis=1) # сортируем столбцы (axis = 1) датафрейма по возрастанию

      Birthday            Name Position    Salary                 Team
0   1996-09-26    Shake Milton       SG   1445697   Philadelphia 76ers
1   1995-09-27  Christian Wood       PF   1645357      Detroit Pistons
2   1998-08-23   PJ Washington       PF   3831840    Charlotte Hornets
3   1988-10-04    Derrick Rose       PG   7317074      Detroit Pistons
4   1995-07-26   Marial Shayok        G     79568   Philadelphia 76ers
..         ...             ...      ...       ...                  ...
445 1992-08-01   Austin Rivers       PG   2174310      Houston Rockets
446 1998-04-22     Harry Giles       PF   2578800     Sacramento Kings
447 1988-04-01     Robin Lopez        C   4767000      Milwaukee Bucks
448 1999-01-04   Collin Sexton       PG   4764960  Cleveland Cavaliers
449 1990-10-21     Ricky Rubio       PG  16200000         Phoenix Suns

[450 rows x 5 columns]

In [157]:
nba.sort_index(axis=1, ascending=False) # сортируем столбцы (axis = 1) датафрейма по убыванию

                    Team    Salary Position            Name   Birthday
0     Philadelphia 76ers   1445697       SG    Shake Milton 1996-09-26
1        Detroit Pistons   1645357       PF  Christian Wood 1995-09-27
2      Charlotte Hornets   3831840       PF   PJ Washington 1998-08-23
3        Detroit Pistons   7317074       PG    Derrick Rose 1988-10-04
4     Philadelphia 76ers     79568        G   Marial Shayok 1995-07-26
..                   ...       ...      ...             ...        ...
445      Houston Rockets   2174310       PG   Austin Rivers 1992-08-01
446     Sacramento Kings   2578800       PF     Harry Giles 1998-04-22
447      Milwaukee Bucks   4767000        C     Robin Lopez 1988-04-01
448  Cleveland Cavaliers   4764960       PG   Collin Sexton 1999-01-04
449         Phoenix Suns  16200000       PG     Ricky Rubio 1990-10-21

[450 rows x 5 columns]

"""---4.5 ЗАДАНИЕ НОВОГО ИНДЕКСА---"""

In [158]:
nba = nba.set_index("Name")
nba

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

"""---4.6 ИЗВЛЕЧЕНИЕ СТОЛБЦОВ ИЗ ОБЪЕКТА DataFrame---"""

"""---4.6.1 Извлечение одного столбца из объекта DateFrame---"""

In [161]:
nba.Salary

Name
Shake Milton       1445697
Christian Wood     1645357
PJ Washington      3831840
Derrick Rose       7317074
Marial Shayok        79568
                    ...
Austin Rivers      2174310
Harry Giles        2578800
Robin Lopez        4767000
Collin Sexton      4764960
Ricky Rubio       16200000
Name: Salary, Length: 450, dtype: int64

In [162]:
nba["Position"] # [] - поддерждивает пробел в названии столбца

Name
Shake Milton      SG
Christian Wood    PF
PJ Washington     PF
Derrick Rose      PG
Marial Shayok      G
                  ..
Austin Rivers     PG
Harry Giles       PF
Robin Lopez        C
Collin Sexton     PG
Ricky Rubio       PG
Name: Position, Length: 450, dtype: object