<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%206.%20%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%D1%81%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%BC%D0%B8%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---6. РАБОТА С ТЕКСТОВЫМИ ДАННЫМИ---"""

"""---6.1 РЕГИСТР БУКВ И ПРОБЕЛЫ---"""

In [1]:
import pandas as pd

In [2]:
inspection = pd.read_csv("chicago_food_inspections.csv")

inspection

                               Name             Risk
0        MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                       JETS PIZZA   Risk 2 (Medium)
2                        ROOM 1520      Risk 3 (Low)
3         MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                     CHARTWELLS       Risk 1 (High)
...                             ...              ...
134229         MR BROWN'S LOUNGE       Risk 1 (High)
134230          CARAMELA  BAKERY       Risk 1 (High)
134231                   McDONALDS   Risk 2 (Medium)
134232                  7 - ELEVEN   Risk 2 (Medium)
134233                  SAVE-A-LOT               Ris

[134234 rows x 2 columns]

In [3]:
inspection["Name"].head().values # получаем ndarray

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       '  MARRIOT MARQUIS CHICAGO  ', ' CHARTWELLS   '], dtype=object)

In [4]:
inspection['Name'].str # атрибут "srt" дает доступ к объекту StringMethods - для работы со строковыми значениями

In [5]:
inspection["Name"].str.lstrip().head() # удаляем лишние пробелы слева

0    MARRIOT MARQUIS CHICAGO
1                   JETS PIZZA
2                    ROOM 1520
3     MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [6]:
inspection["Name"].str.rstrip().head() # удаляем лишние пробелы справа

0      MARRIOT MARQUIS CHICAGO
1                   JETS PIZZA
2                    ROOM 1520
3      MARRIOT MARQUIS CHICAGO
4                   CHARTWELLS
Name: Name, dtype: object

In [7]:
inspection["Name"].str.strip().head() # удаляем лишние пробелы И слева И справа сразу

0    MARRIOT MARQUIS CHICAGO
1                 JETS PIZZA
2                  ROOM 1520
3    MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [8]:
inspection["Name"] = inspection["Name"].str.strip() # создали новый объект Series без пробелов на основе столбца Name и перезаписали в существующий столбец

In [9]:
inspection.columns

Index(['Name', 'Risk'], dtype='object')

In [10]:
# цикл по столбцам (переменная column) для удаления лишних пробелов разово везде
for column in inspection.columns:
  inspection[column] = inspection[column].str.strip() # inspection[column] = nspection["Name"]; inspection[column].str.strip() = inspection["Name"].str.strip()

In [11]:
inspection["Name"].str.lower().head()

0    marriot marquis chicago
1                 jets pizza
2                  room 1520
3    marriot marquis chicago
4                 chartwells
Name: Name, dtype: object

In [12]:
steaks = pd.Series(["porterhouse", "filet mignon", "ribeye"])

steaks

0     porterhouse
1    filet mignon
2          ribeye
dtype: object

In [13]:
steaks.str.upper() # верхний регистр

0     PORTERHOUSE
1    FILET MIGNON
2          RIBEYE
dtype: object

In [14]:
inspection["Name"].str.capitalize().head() # приводим в верхний регистр только первую букву каждой строки столбца

0    Marriot marquis chicago
1                 Jets pizza
2                  Room 1520
3    Marriot marquis chicago
4                 Chartwells
Name: Name, dtype: object

In [15]:
inspection["Name"].str.title().head() # приводим в верхний регистр первую букву каждого слова в строке столбца

0    Marriot Marquis Chicago
1                 Jets Pizza
2                  Room 1520
3    Marriot Marquis Chicago
4                 Chartwells
Name: Name, dtype: object

"""---6.2 СРЕЗЫ СТРОКОВЫХ ЗНАЧЕНИЙ---"""

In [24]:
inspection['Risk'].head()

0      Risk 1 (High)
1    Risk 2 (Medium)
2       Risk 3 (Low)
3      Risk 1 (High)
4      Risk 1 (High)
Name: Risk, dtype: object

In [18]:
len(inspection)

134234

In [19]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan,
       'Ris'], dtype=object)

In [21]:
inspection = inspection.dropna(subset=["Risk"]) # удаляем пустые строки столбца "Risk"

In [22]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', 'Ris'],
      dtype=object)

In [25]:
inspection = inspection.replace(
    to_replace="All",
    value="Risk 4 (Extreme)"
)

In [26]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)', 'Ris'], dtype=object)

In [27]:
inspection = inspection.replace(
    to_replace="Ris",
    value="Risk 1 (High +)"
)

In [28]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)', 'Risk 1 (High +)'], dtype=object)

"""---6.3 СРЕЗЫ СТРОКОВЫХ ЗНАЧЕНИЙ И ЗАМЕНА СИМВОЛОВ---"""

In [29]:
inspection["Risk"].str.slice(5, 6).head() # для извлечения подстрок символов из строковых значений по позициям индексов можно воспользоваться методом slice

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [30]:
inspection["Risk"].str[5:6].head() # аналог строки выше (синтаксис срезов списков языка Python)

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object