<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%203.%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0%20Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---3. МЕТОДЫ КЛАССА SERIES---"""

"""---3.1 ИМПОРТ НАБОРА ДАННЫХ С ПОМОЩЬЮ ФУНКЦИИ READ_CSV---"""

In [16]:
import pandas as pd

In [2]:
pd.read_csv("pokemon.csv")

         Pokemon            Type
0      Bulbasaur  Grass / Poison
1        Ivysaur  Grass / Poison
2       Venusaur  Grass / Poison
3     Charmander            Fire
4     Charmeleon            Fire
..           ...             ...
804    Stakataka    Rock / Steel
805  Blacephalon    Fire / Ghost
806      Zeraora        Electric
807       Meltan           Steel
808     Melmetal           Steel

[809 rows x 2 columns]

In [21]:
pokemon = pd.read_csv("pokemon.csv", index_col="Pokemon")
pokemon

                       Type
Pokemon
Bulbasaur    Grass / Poison
Ivysaur      Grass / Poison
Venusaur     Grass / Poison
Charmander             Fire
Charmeleon             Fire
...                     ...
Stakataka      Rock / Steel
Blacephalon    Fire / Ghost
Zeraora            Electric
Meltan                Steel
Melmetal              Steel

[809 rows x 1 columns]

In [23]:
pd.read_csv("google_stocks.csv", parse_dates=["Date"]).head()

        Date  Close
0 2004-08-19  49.98
1 2004-08-20  53.95
2 2004-08-23  54.50
3 2004-08-24  52.24
4 2004-08-25  52.80

In [30]:
google = pd.read_csv("google_stocks.csv", parse_dates=["Date"], index_col="Date").head()
google

            Close
Date
2004-08-19  49.98
2004-08-20  53.95
2004-08-23  54.50
2004-08-24  52.24
2004-08-25  52.80