<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%206.%20%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%D1%81%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%BC%D0%B8%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---6. РАБОТА С ТЕКСТОВЫМИ ДАННЫМИ---"""

"""---6.1 РЕГИСТР БУКВ И ПРОБЕЛЫ---"""

In [28]:
import pandas as pd

In [29]:
inspection = pd.read_csv("chicago_food_inspections.csv")

inspection

                               Name             Risk
0        MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                       JETS PIZZA   Risk 2 (Medium)
2                        ROOM 1520      Risk 3 (Low)
3         MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                     CHARTWELLS       Risk 1 (High)
...                             ...              ...
134229         MR BROWN'S LOUNGE       Risk 1 (High)
134230          CARAMELA  BAKERY       Risk 1 (High)
134231                   McDONALDS   Risk 2 (Medium)
134232                  7 - ELEVEN   Risk 2 (Medium)
134233                  SAVE-A-LOT               Ris

[134234 rows x 2 columns]

In [30]:
inspection["Name"].head().values # получаем ndarray

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       '  MARRIOT MARQUIS CHICAGO  ', ' CHARTWELLS   '], dtype=object)

In [31]:
inspection['Name'].str # атрибут "srt" дает доступ к объекту StringMethods - для работы со строковыми значениями

In [32]:
inspection["Name"].str.lstrip().head() # удаляем лишние пробелы слева

0    MARRIOT MARQUIS CHICAGO
1                   JETS PIZZA
2                    ROOM 1520
3     MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [33]:
inspection["Name"].str.rstrip().head() # удаляем лишние пробелы справа

0      MARRIOT MARQUIS CHICAGO
1                   JETS PIZZA
2                    ROOM 1520
3      MARRIOT MARQUIS CHICAGO
4                   CHARTWELLS
Name: Name, dtype: object

In [34]:
inspection["Name"].str.strip().head() # удаляем лишние пробелы И слева И справа сразу

0    MARRIOT MARQUIS CHICAGO
1                 JETS PIZZA
2                  ROOM 1520
3    MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [35]:
inspection["Name"] = inspection["Name"].str.strip() # создали новый объект Series без пробелов на основе столбца Name и перезаписали в существующий столбец

In [36]:
inspection.columns

Index(['Name', 'Risk'], dtype='object')

In [37]:
# цикл по столбцам (переменная column) для удаления лишних пробелов разово везде
for column in inspection.columns:
  inspection[column] = inspection[column].str.strip() # inspection[column] = nspection["Name"]; inspection[column].str.strip() = inspection["Name"].str.strip()

In [38]:
inspection["Name"].str.lower().head()

0    marriot marquis chicago
1                 jets pizza
2                  room 1520
3    marriot marquis chicago
4                 chartwells
Name: Name, dtype: object

In [39]:
steaks = pd.Series(["porterhouse", "filet mignon", "ribeye"])

steaks

0     porterhouse
1    filet mignon
2          ribeye
dtype: object

In [40]:
steaks.str.upper() # верхний регистр

0     PORTERHOUSE
1    FILET MIGNON
2          RIBEYE
dtype: object

In [41]:
inspection["Name"].str.capitalize().head() # приводим в верхний регистр только первую букву каждой строки столбца

0    Marriot marquis chicago
1                 Jets pizza
2                  Room 1520
3    Marriot marquis chicago
4                 Chartwells
Name: Name, dtype: object

In [42]:
inspection["Name"].str.title().head() # приводим в верхний регистр первую букву каждого слова в строке столбца

0    Marriot Marquis Chicago
1                 Jets Pizza
2                  Room 1520
3    Marriot Marquis Chicago
4                 Chartwells
Name: Name, dtype: object

"""---6.2 СРЕЗЫ СТРОКОВЫХ ЗНАЧЕНИЙ---"""

In [43]:
inspection['Risk'].head()

0      Risk 1 (High)
1    Risk 2 (Medium)
2       Risk 3 (Low)
3      Risk 1 (High)
4      Risk 1 (High)
Name: Risk, dtype: object

In [44]:
len(inspection)

134234

In [45]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan,
       'Ris'], dtype=object)

In [46]:
inspection = inspection.dropna(subset=["Risk"]) # удаляем пустые строки столбца "Risk"

In [47]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', 'Ris'],
      dtype=object)

In [48]:
inspection = inspection.replace(
    to_replace="All",
    value="Risk 4 (Extreme)"
)

In [49]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)', 'Ris'], dtype=object)

In [50]:
inspection = inspection.replace(
    to_replace="Ris",
    value="Risk 1 (High +)"
)

In [51]:
inspection["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)', 'Risk 1 (High +)'], dtype=object)

"""---6.3 СРЕЗЫ СТРОКОВЫХ ЗНАЧЕНИЙ И ЗАМЕНА СИМВОЛОВ---"""

In [52]:
inspection["Risk"].str.slice(5, 6).head() # для извлечения подстрок символов из строковых значений по позициям индексов можно воспользоваться методом slice. первый аргусмент - начало (включая), второй - конец (НЕ включая)

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [53]:
inspection["Risk"].str[5:6].head() # аналог строки выше (синтаксис срезов списков языка Python)

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [54]:
inspection["Risk"].str.slice(8).head() # извлекаем символы, начиная с позиции индекса 8 до конца строковых значений

0      High)
1    Medium)
2       Low)
3      High)
4      High)
Name: Risk, dtype: object

In [55]:
inspection["Risk"].str[8:].head() # аналог строки выше

0      High)
1    Medium)
2       Low)
3      High)
4      High)
Name: Risk, dtype: object

In [56]:
inspection["Risk"].str.slice(8, -1).head() # убираем последний знак строки из слайса

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [57]:
inspection["Risk"].str[8:-1].head() # аналог строки выше

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

Для удаления закрывающих скобок можно также воспользоваться методом
str.replace, заменяя закрывающую скобку пустой строкой
—
строковое значение без символов.
Все методы str возвращают новый объект Series со своим собственным атрибутом str  .Это позволяет последовательно связывать цепочкой несколько
строковых методов, просто ссылаясь при вызове каждого метода на атрибут str  .

In [58]:
inspection["Risk"].str.slice(8).str.replace(")", "").head()

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

"""---6.4 БУЛЕВЫ МЕТОДЫ---"""

In [59]:
inspection["Name"].str.lower().str.contains("pizza").head() # понижаем регистр и проверяем строку на соотвестве подстроке "pizza"

0    False
1     True
2    False
3    False
4    False
Name: Name, dtype: bool

In [60]:
has_pizza = inspection["Name"].str.lower().str.contains("pizza") # возращаем DataFrame относительно Series выше

inspection[has_pizza]

                                 Name             Risk
1                          JETS PIZZA  Risk 2 (Medium)
19      NANCY'S HOME OF STUFFED PIZZA    Risk 1 (High)
27         NARY'S GRILL & PIZZA ,INC.    Risk 1 (High)
29                NARYS GRILL & PIZZA    Risk 1 (High)
68                      COLUTAS PIZZA    Risk 1 (High)
...                               ...              ...
134147                PURGATORY PIZZA    Risk 1 (High)
134155               CIPRIANI'S PIZZA    Risk 1 (High)
134165   PIEZANO'S PIZZA & GRINDER CO    Risk 1 (High)
134185                 CHOLIE'S PIZZA    Risk 1 (High)
134203       PAPA RAY'S PIZZA & WINGS    Risk 1 (High)

[3481 rows x 2 columns]

In [61]:
inspection["Name"].str.lower().str.startswith("tacos").head() # проверяем начинается ли подстрока с определенного текста (startswith)

0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [62]:
start_with_tacos = (
    inspection["Name"].str.lower().str.startswith("tacos")
)

inspection[start_with_tacos]

                         Name           Risk
69               TACOS NIETOS  Risk 1 (High)
556       TACOS EL TIO 2 INC.  Risk 1 (High)
675          TACOS DON GABINO  Risk 1 (High)
958       TACOS EL TIO 2 INC.  Risk 1 (High)
1036      TACOS EL TIO 2 INC.  Risk 1 (High)
...                       ...            ...
119942         TACOS DON CUCO  Risk 1 (High)
122443          TACOS DE LUNA  Risk 1 (High)
126785         TACOS DON CUCO  Risk 1 (High)
132194  TACOS MARIO'S LIMITED  Risk 1 (High)
133893          TACOS DE LUNA  Risk 1 (High)

[90 rows x 2 columns]

In [63]:
# ищем то же самое, только в конце в конце строки
end_with_tacos = (
    inspection["Name"].str.lower().str.endswith("tacos")
)

inspection[end_with_tacos]

                Name           Risk
382     LAZO'S TACOS  Risk 1 (High)
569     LAZO'S TACOS  Risk 1 (High)
2652    FLYING TACOS   Risk 3 (Low)
3250    JONY'S TACOS  Risk 1 (High)
3812    PACO'S TACOS  Risk 1 (High)
...              ...            ...
132004  AZTECA TACOS  Risk 1 (High)
132421  HUNGRY TACOS  Risk 1 (High)
133230     ZACATACOS  Risk 1 (High)
133971  HUNGRY TACOS  Risk 1 (High)
133983  PAPI'S TACOS  Risk 1 (High)

[269 rows x 2 columns]

"""---6.5 РАЗБИЕНИЕ СТРОКОВЫХ ЗНАЧЕНИЙ---"""

In [64]:
customers = pd.read_csv("customers.csv")

customers

                     Name                                            Address
0           Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1       Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2         Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3     Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4          Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
...                   ...                                                ...
9956        Dana Browning  762 Andrew Views Apt. 254, North Paul, New Mex...
9957      Amanda Anderson  44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958           Eric Davis  73015 Michelle Squares, Watsonville, West Virg...
9959     Taylor Hernandez       129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     Sherry Nicholson   355 Griffin Valley, Davidtown, New Mexico, 17581

[9961 rows x 2 columns]

In [65]:
customers["Name"].str.len().head() # определяем длину строки

0    13
1    17
2    15
3    19
4    14
Name: Name, dtype: int64

In [66]:
phone_number = "555-123-4567"

phone_number.split("-") # разбиваем строковое значение по указанному разделителю

['555', '123', '4567']

In [67]:
customers["Name"].str.split(pat=" ").head()

0           [Frank, Manning]
1       [Elizabeth, Johnson]
2         [Donald, Stephens]
3    [Michael, Vincent, III]
4          [Jasmine, Zamora]
Name: Name, dtype: object

In [68]:
customers["Name"].str.split(pat=" ").str.len().head()

0    2
1    2
2    2
3    3
4    2
Name: Name, dtype: int64

In [69]:
customers["Name"].str.split(pat=" ", n=1).head() # n=1 - задаем максимальное кол-во разбиений (идем до первого пробела)

0          [Frank, Manning]
1      [Elizabeth, Johnson]
2        [Donald, Stephens]
3    [Michael, Vincent III]
4         [Jasmine, Zamora]
Name: Name, dtype: object

In [70]:
customers["Name"].str.split(pat=" ", n=1).str.get(0).head() # get - извлекает значение из спска на основе позиции индекса

0        Frank
1    Elizabeth
2       Donald
3      Michael
4      Jasmine
Name: Name, dtype: object

In [71]:
customers["Name"].str.split(pat=" ", n=1).str.get(1).head()

0        Manning
1        Johnson
2       Stephens
3    Vincent III
4         Zamora
Name: Name, dtype: object

In [72]:
customers["Name"].str.split(pat=" ", n=1).str.get(-1).head() # -1 - извлекает последний элемент списка (удобно, если длины списков различаются)

0        Manning
1        Johnson
2       Stephens
3    Vincent III
4         Zamora
Name: Name, dtype: object

In [73]:
customers["Name"].str.split(
    pat= " ",
    n=1,
    expand=True # возвращаем DataFrame с разбиением списка на столбцы
).head()

           0            1
0      Frank      Manning
1  Elizabeth      Johnson
2     Donald     Stephens
3    Michael  Vincent III
4    Jasmine       Zamora

In [74]:
customers["Name"].str.split(
    pat= " ",
    expand=True
).head() # если не задать n, то pandas задаст автоматически None в строках, где элементов недостаточно

           0         1     2
0      Frank   Manning  None
1  Elizabeth   Johnson  None
2     Donald  Stephens  None
3    Michael   Vincent   III
4    Jasmine    Zamora  None

In [75]:
customers[["First Name", "Last Name"]] = customers[
    "Name"
].str.split(pat= " ", n=1, expand=True)

customers

,Name,Address,First Name,Last Name
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [76]:
customers = customers.drop(labels="Name", axis="columns")

In [77]:
customers.head()

                                             Address First Name    Last Name
0  6461 Quinn Groves, East Matthew, New Hampshire...      Frank      Manning
1  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...  Elizabeth      Johnson
2  19120 Fleming Manors, Prestonstad, Montana, 23495     Donald     Stephens
3       441 Olivia Creek, Jimmymouth, Georgia, 82991    Michael  Vincent III
4  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...    Jasmine       Zamora

"""---6.6 УПРАЖНЕНИЯ---"""

In [78]:
customers

,Address,First Name,Last Name
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...
9956,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [79]:
customers[["Street", "City", "State", "Zip"]] = customers[
    "Address"
].str.split(pat=", ", n=3, expand=True)

customers.head()

,Address,First Name,Last Name,Street,City,State,Zip
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252

In [80]:
customers = customers.drop(labels="Address", axis="columns")

In [81]:
customers.head()

,First Name,Last Name,Street,City,State,Zip
0,Frank,Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth,Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald,Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael,Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine,Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252

In [82]:
customers["Street"].head()

0             6461 Quinn Groves
1    1360 Tracey Ports Apt. 419
2          19120 Fleming Manors
3              441 Olivia Creek
4    4246 Chelsey Ford Apt. 310
Name: Street, dtype: object

In [83]:
customers["Street"].str.replace(
    "\d{4,}", "*", regex=True
).head()

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_4319/1650180660.py:2: SyntaxWarning: invalid escape sequence '\d'
  "\d{4,}", "*", regex=True

0             * Quinn Groves
1    * Tracey Ports Apt. 419
2           * Fleming Manors
3           441 Olivia Creek
4    * Chelsey Ford Apt. 310
Name: Street, dtype: object