<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%204.%20%D0%9E%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%20DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---4. ОБЪЕКТ DataFrame---"""

"""---4.1 ОБЗОР DataFrame---"""

"""---4.1.1 Создание объекта DataFrame на основе ассоциативного массива---"""

In [165]:
import pandas as pd
import numpy as np

In [166]:
city_data = {
    "City": ["New York", "Paris", "Barcelona", "Rome"],
    "Country": ["United States", "France", "Spain", "Italy"],
    "Population": [8600000, 2141000, 5515000, 2873000]
}

cities = pd.DataFrame(city_data)
cities

        City        Country  Population
0   New York  United States     8600000
1      Paris         France     2141000
2  Barcelona          Spain     5515000
3       Rome          Italy     2873000

In [167]:
cities.T # транспонировали таблицу

                        0        1          2        3
City             New York    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

"""---4.1.2 Создание объекта DataFrame на основе ndarray библиотеки NumPy---"""

In [168]:
random_data = np.random.randint(1, 101, [3, 5])
random_data

array([[60, 33, 42, 93, 84],
       [92,  4, 24, 80,  6],
       [52, 83, 88, 62, 70]])

In [169]:
pd.DataFrame(data=random_data)

    0   1   2   3   4
0  60  33  42  93  84
1  92   4  24  80   6
2  52  83  88  62  70

In [170]:
row_labels = ["Morning", "Afternoon", "Evening"]
temperatures = pd.DataFrame(random_data,
                            index=row_labels)
temperatures

            0   1   2   3   4
Morning    60  33  42  93  84
Afternoon  92   4  24  80   6
Evening    52  83  88  62  70

In [171]:
row_labels = ["Morning", "Afternoon", "Evening"]
column_labels = (
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday"
)
temperatures = pd.DataFrame(random_data,
                            index=row_labels,
                            columns=column_labels)
temperatures

           Monday  Tuesday  Wednesday  Thursday  Friday
Morning        60       33         42        93      84
Afternoon      92        4         24        80       6
Evening        52       83         88        62      70

In [172]:
row_labels = ["Morning", "Afternoon", "Morning"]
column_labels = (
    "Monday",
    "Tuesday",
    "Wednesday",
    "Tuesday",
    "Friday"
)
temperatures = pd.DataFrame(random_data,
                            index=row_labels,
                            columns=column_labels)
temperatures

           Monday  Tuesday  Wednesday  Tuesday  Friday
Morning        60       33         42       93      84
Afternoon      92        4         24       80       6
Morning        52       83         88       62      70

"""---4.2 ОБЩИЕ ЧЕРТЫ SERIES И DataFrame---"""

"""---4.2.1 Импорт объекта DateFrame с помощью функции read_csv---"""

In [173]:
nba = pd.read_csv("nba.csv",
            parse_dates=["Birthday"])

nba

/tmp/ipykernel_1911/2611377350.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("nba.csv",

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

"""---4.2.2 Атрибуты Series и DataFrame: сходство и различие---"""

In [174]:
pd.Series([1, 2, 3]).dtype

dtype('int64')

In [175]:
nba.dtypes

Name                object
Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [176]:
nba.dtypes.value_counts()

object            3
datetime64[ns]    1
int64             1
Name: count, dtype: int64

In [177]:
nba.index

RangeIndex(start=0, stop=450, step=1)

In [178]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [179]:
nba.ndim

2

In [180]:
nba.shape

(450, 5)

In [181]:
nba.size

2250

In [182]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [183]:
nba.count().sum()

np.int64(2250)

In [184]:
data = {
    "A": [1, np.nan],
    "B": [2, 3]
}

df = pd.DataFrame(data)

df

     A  B
0  1.0  2
1  NaN  3

In [185]:
df.size

4

In [186]:
df.count()

A    1
B    2
dtype: int64

In [187]:
df.count().sum()

np.int64(3)

"""---4.2.3 Общие методы Series и  DataFrame---"""

In [188]:
nba.head(2)

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [189]:
nba.tail(3)

              Name                 Team Position   Birthday    Salary
447    Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448  Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449    Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

In [190]:
nba.sample(3) # случайное извлечние заданного количества строк

                 Name                Team Position   Birthday    Salary
235        Al Horford  Philadelphia 76ers        C 1986-06-03  28000000
81        Adam Mokoka       Chicago Bulls        G 1998-07-18     79568
107  Denzel Valentine       Chicago Bulls       SF 1993-11-16   3377568

In [191]:
nba.nunique() # количество уникальных значений в каждом из столбцов датафрейма

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [192]:
nba.max()

Name             Zylan Cheatham
Team         Washington Wizards
Position                     SG
Birthday    2000-12-23 00:00:00
Salary                 40231758
dtype: object

In [193]:
nba.min()

Name               Aaron Gordon
Team              Atlanta Hawks
Position                      C
Birthday    1977-01-26 00:00:00
Salary                    79568
dtype: object

In [194]:
nba.nlargest(n=4, columns="Salary") # извлекаем максимальное значение по столбцу из набора данных в заданном количестве

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000

In [195]:
nba.nsmallest(n=3, columns="Birthday") # извлекаем минимальное значение по столбцу из набора данных в заданном количестве

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

In [196]:
nba["Salary"].sum()

np.int64(3444112694)

In [197]:
nba.sum(numeric_only=True)

Salary    3444112694
dtype: int64

In [198]:
nba.mean(numeric_only=True)

Salary    7.653584e+06
dtype: float64

In [199]:
nba.median(numeric_only=True)

Salary    3303074.5
dtype: float64

In [200]:
nba.mode(numeric_only=True)

   Salary
0   79568

In [201]:
nba.std(numeric_only=True)

Salary    9.288810e+06
dtype: float64

"""---4.3 СОРТИРОВКА ОБЪЕКТА DatFrame---"""

"""---4.3.1 Сортировка по одному столбцу---"""

In [202]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [203]:
nba.sort_values("Name")

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [204]:
nba.sort_values("Name", ascending=False).head()

                Name                  Team Position   Birthday    Salary
248   Zylan Cheatham  New Orleans Pelicans       SF 1995-11-17     79568
137  Zion Williamson  New Orleans Pelicans        F 2000-07-06   9757440
312     Zhaire Smith    Philadelphia 76ers       SG 1999-06-04   3058800
302     Zach Norvell    Los Angeles Lakers       SG 1997-12-09     79568
159      Zach LaVine         Chicago Bulls       PG 1995-03-10  19500000

In [205]:
nba.sort_values("Birthday", ascending=False).head() # аналог метода nsmallest

                    Name                  Team Position   Birthday   Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23  3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25   898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06  9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14  7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13   898310

In [206]:
nba.nlargest(n=5, columns="Birthday")

                    Name                  Team Position   Birthday   Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23  3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25   898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06  9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14  7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13   898310

"""---4.3.2 Сортировка по нескольким столбцу---"""

In [207]:
nba.sort_values(["Team", "Name"])

                Name                Team Position   Birthday    Salary
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
..               ...                 ...      ...        ...       ...
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000

[450 rows x 5 columns]

In [208]:
nba.sort_values(["Team", "Name"], ascending=False)

                Name                Team Position   Birthday    Salary
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
..               ...                 ...      ...        ...       ...
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000

[450 rows x 5 columns]

In [209]:
nba.sort_values(
    ["Team", "Salary"],
    ascending=[True, False]) # сортируем в разном порядке. Столбец Team по возрастанию, столбец Salary по убыванию

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

In [210]:
nba = nba.sort_values(
    ["Team", "Salary"],
    ascending=[True, False])

nba

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

"""---4.4 СОРТИРОВКА ПО ИНДЕКСУ---"""

In [211]:
nba.head()

                 Name           Team Position   Birthday    Salary
111  Chandler Parsons  Atlanta Hawks       SF 1988-10-25  25102512
28        Evan Turner  Atlanta Hawks       PG 1988-10-27  18606556
167      Allen Crabbe  Atlanta Hawks       SG 1992-04-09  18500000
213   De'Andre Hunter  Atlanta Hawks       SF 1997-12-02   7068360
339     Jabari Parker  Atlanta Hawks       PF 1995-03-15   6500000

"""---4.4.1 Сортировка по индексу строк---"""

In [212]:
nba.sort_index().head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [213]:
nba.sort_index(ascending=False).head()

              Name                 Team Position   Birthday    Salary
449    Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000
448  Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
447    Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
446    Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
445  Austin Rivers      Houston Rockets       PG 1992-08-01   2174310

In [214]:
nba = nba.sort_index()
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

"""---4.4.2 Сортировка по индексу столбцов---"""

In [215]:
nba.sort_index(axis=1) # сортируем столбцы (axis = 1) датафрейма по возрастанию

      Birthday            Name Position    Salary                 Team
0   1996-09-26    Shake Milton       SG   1445697   Philadelphia 76ers
1   1995-09-27  Christian Wood       PF   1645357      Detroit Pistons
2   1998-08-23   PJ Washington       PF   3831840    Charlotte Hornets
3   1988-10-04    Derrick Rose       PG   7317074      Detroit Pistons
4   1995-07-26   Marial Shayok        G     79568   Philadelphia 76ers
..         ...             ...      ...       ...                  ...
445 1992-08-01   Austin Rivers       PG   2174310      Houston Rockets
446 1998-04-22     Harry Giles       PF   2578800     Sacramento Kings
447 1988-04-01     Robin Lopez        C   4767000      Milwaukee Bucks
448 1999-01-04   Collin Sexton       PG   4764960  Cleveland Cavaliers
449 1990-10-21     Ricky Rubio       PG  16200000         Phoenix Suns

[450 rows x 5 columns]

In [216]:
nba.sort_index(axis=1, ascending=False) # сортируем столбцы (axis = 1) датафрейма по убыванию

                    Team    Salary Position            Name   Birthday
0     Philadelphia 76ers   1445697       SG    Shake Milton 1996-09-26
1        Detroit Pistons   1645357       PF  Christian Wood 1995-09-27
2      Charlotte Hornets   3831840       PF   PJ Washington 1998-08-23
3        Detroit Pistons   7317074       PG    Derrick Rose 1988-10-04
4     Philadelphia 76ers     79568        G   Marial Shayok 1995-07-26
..                   ...       ...      ...             ...        ...
445      Houston Rockets   2174310       PG   Austin Rivers 1992-08-01
446     Sacramento Kings   2578800       PF     Harry Giles 1998-04-22
447      Milwaukee Bucks   4767000        C     Robin Lopez 1988-04-01
448  Cleveland Cavaliers   4764960       PG   Collin Sexton 1999-01-04
449         Phoenix Suns  16200000       PG     Ricky Rubio 1990-10-21

[450 rows x 5 columns]

"""---4.5 ЗАДАНИЕ НОВОГО ИНДЕКСА---"""

In [217]:
nba = nba.set_index("Name")
nba

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

"""---4.6 ИЗВЛЕЧЕНИЕ СТОЛБЦОВ ИЗ ОБЪЕКТА DataFrame---"""

"""---4.6.1 Извлечение одного столбца из объекта DateFrame---"""

In [218]:
nba.Salary

Name
Shake Milton       1445697
Christian Wood     1645357
PJ Washington      3831840
Derrick Rose       7317074
Marial Shayok        79568
                    ...
Austin Rivers      2174310
Harry Giles        2578800
Robin Lopez        4767000
Collin Sexton      4764960
Ricky Rubio       16200000
Name: Salary, Length: 450, dtype: int64

In [219]:
nba["Position"] # [] - поддерждивает пробел в названии столбца

Name
Shake Milton      SG
Christian Wood    PF
PJ Washington     PF
Derrick Rose      PG
Marial Shayok      G
                  ..
Austin Rivers     PG
Harry Giles       PF
Robin Lopez        C
Collin Sexton     PG
Ricky Rubio       PG
Name: Position, Length: 450, dtype: object

"""---4.6.2 Извлечение нескольких столбцов из объекта DataFrame---"""

In [220]:
nba[["Salary", "Birthday"]] # извлечение будет выполнено в порядке следования (как указано)

                  Salary   Birthday
Name
Shake Milton     1445697 1996-09-26
Christian Wood   1645357 1995-09-27
PJ Washington    3831840 1998-08-23
Derrick Rose     7317074 1988-10-04
Marial Shayok      79568 1995-07-26
...                  ...        ...
Austin Rivers    2174310 1992-08-01
Harry Giles      2578800 1998-04-22
Robin Lopez      4767000 1988-04-01
Collin Sexton    4764960 1999-01-04
Ricky Rubio     16200000 1990-10-21

[450 rows x 2 columns]

In [221]:
nba[["Birthday", "Salary"]]

                 Birthday    Salary
Name
Shake Milton   1996-09-26   1445697
Christian Wood 1995-09-27   1645357
PJ Washington  1998-08-23   3831840
Derrick Rose   1988-10-04   7317074
Marial Shayok  1995-07-26     79568
...                   ...       ...
Austin Rivers  1992-08-01   2174310
Harry Giles    1998-04-22   2578800
Robin Lopez    1988-04-01   4767000
Collin Sexton  1999-01-04   4764960
Ricky Rubio    1990-10-21  16200000

[450 rows x 2 columns]

In [222]:
nba.select_dtypes(include="object") # извлекаем из датафрейма только (include) тип object

                               Team Position
Name
Shake Milton     Philadelphia 76ers       SG
Christian Wood      Detroit Pistons       PF
PJ Washington     Charlotte Hornets       PF
Derrick Rose        Detroit Pistons       PG
Marial Shayok    Philadelphia 76ers        G
...                             ...      ...
Austin Rivers       Houston Rockets       PG
Harry Giles        Sacramento Kings       PF
Robin Lopez         Milwaukee Bucks        C
Collin Sexton   Cleveland Cavaliers       PG
Ricky Rubio            Phoenix Suns       PG

[450 rows x 2 columns]

In [223]:
nba.select_dtypes(exclude=["object", "int64"]) # извлекаем из датафрейма все, кроме (exclude) указанных типов данных

                 Birthday
Name
Shake Milton   1996-09-26
Christian Wood 1995-09-27
PJ Washington  1998-08-23
Derrick Rose   1988-10-04
Marial Shayok  1995-07-26
...                   ...
Austin Rivers  1992-08-01
Harry Giles    1998-04-22
Robin Lopez    1988-04-01
Collin Sexton  1999-01-04
Ricky Rubio    1990-10-21

[450 rows x 1 columns]

"""---4.7 ИЗВЛЕЧЕНИЕ СТРОК ИЗ ОБЪЕКТА DateFrame---"""

"""---4.7.1 Извлечение строк по метке индекса---"""

In [224]:
nba.loc["LeBron James"] # не выдает ошибку, так как метка индксе в нашем надре = "Name"

Team         Los Angeles Lakers
Position                     PF
Birthday    1984-12-30 00:00:00
Salary                 37436858
Name: LeBron James, dtype: object

In [225]:
nba.loc[["Kawhi Leonard", "Paul George"]] # несколько строк, индексы которых помещены в [[]]

                               Team Position   Birthday    Salary
Name
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556

In [226]:
nba.loc[["Paul George", "Kawhi Leonard"]] # [[]] организует строки по порядку вхождения их меток индекса в список

                               Team Position   Birthday    Salary
Name
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000

In [227]:
nba.sort_index().loc["Otto Porter":"Patrick Beverley"]

                                  Team Position   Birthday    Salary
Name
Otto Porter              Chicago Bulls       SF 1993-06-03  27250576
PJ Dozier               Denver Nuggets       PG 1996-10-25     79568
PJ Washington        Charlotte Hornets       PF 1998-08-23   3831840
Pascal Siakam          Toronto Raptors       PF 1994-04-02   2351838
Pat Connaughton        Milwaukee Bucks       SG 1993-01-06   1723050
Patrick Beverley  Los Angeles Clippers       PG 1988-07-12  12345680

In [228]:
players = ["Otto Porter", "PJ Dozier", "PJ Washington"]
players[0:2]

['Otto Porter', 'PJ Dozier']

In [229]:
nba.sort_index().loc["Zach Collins":]

                                   Team Position   Birthday    Salary
Name
Zach Collins     Portland Trail Blazers        C 1997-11-19   4240200
Zach LaVine               Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell         Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith         Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson    New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham     New Orleans Pelicans       SF 1995-11-17     79568

In [230]:
nba.sort_index().loc[:"Al Horford"]

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
Al Horford            Philadelphia 76ers        C 1986-06-03  28000000

"""---4.7.2 Извлечение строк по позиции индекса---"""

In [231]:
nba.iloc[300]

Team             Denver Nuggets
Position                     PF
Birthday    1999-04-03 00:00:00
Salary                  1416852
Name: Jarred Vanderbilt, dtype: object

In [232]:
nba.iloc[[100, 200, 300, 400]]

                                Team Position   Birthday   Salary
Name
Brian Bowen           Indiana Pacers       SG 1998-10-02    79568
Marco Belinelli    San Antonio Spurs       SF 1986-03-25  5846154
Jarred Vanderbilt     Denver Nuggets       PF 1999-04-03  1416852
Louis King           Detroit Pistons        F 1999-04-06    79568

In [233]:
nba.iloc[400:404]

                                    Team Position   Birthday    Salary
Name
Louis King               Detroit Pistons        F 1999-04-06     79568
Kostas Antetokounmpo  Los Angeles Lakers       PF 1997-11-20     79568
Rodions Kurucs             Brooklyn Nets       PF 1998-02-05   1699236
Spencer Dinwiddie          Brooklyn Nets       PG 1993-04-06  10605600

In [234]:
nba.iloc[:2]

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [235]:
nba.iloc[447:]

                              Team Position   Birthday    Salary
Name
Robin Lopez        Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio           Phoenix Suns       PG 1990-10-21  16200000

In [236]:
nba.iloc[-10:-6] # извлекаем строки в обратном порядке (с конца набора данных)

                                    Team Position   Birthday   Salary
Name
Jared Dudley          Los Angeles Lakers       PF 1985-07-10  2564753
Max Strus                  Chicago Bulls       SG 1996-03-28    79568
Kevon Looney       Golden State Warriors        C 1996-02-06  4464286
Willy Hernangomez      Charlotte Hornets        C 1994-05-27  1557250

In [237]:
nba.iloc[0:10:2] # извлекаем строки с шагом в 2 пункта

                             Team Position   Birthday    Salary
Name
Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
PJ Washington   Charlotte Hornets       PF 1998-08-23   3831840
Marial Shayok  Philadelphia 76ers        G 1995-07-26     79568
Kendrick Nunn          Miami Heat       SG 1995-08-03   1416852
Brook Lopez       Milwaukee Bucks        C 1988-04-01  12093024

"""---4.7.3 Извлечение. значений из конкретных столбцов---"""

In [238]:
nba.loc["Giannis Antetokounmpo", "Team"]

'Milwaukee Bucks'

In [239]:
nba.loc["James Harden", ["Position", "Birthday"]]

Position                     PG
Birthday    1989-08-26 00:00:00
Name: James Harden, dtype: object

In [240]:
nba.loc[
    ["Russell Westbrook", "Anthony Davis"],
    ["Team", "Salary"]
]

                                 Team    Salary
Name
Russell Westbrook     Houston Rockets  38506482
Anthony Davis      Los Angeles Lakers  27093019

In [241]:
nba.loc["Joel Embiid", "Position":"Salary"] # укащывать названия столбцов необходимо в порядке их появления в наборе данных

Position                      C
Birthday    1994-03-16 00:00:00
Salary                 27504630
Name: Joel Embiid, dtype: object

In [242]:
nba.iloc[57, 3]

np.int64(796806)

In [243]:
nba.iloc[100:104,:3]

                             Team Position   Birthday
Name
Brian Bowen        Indiana Pacers       SG 1998-10-02
Aaron Holiday      Indiana Pacers       PG 1996-09-30
Troy Daniels   Los Angeles Lakers       SG 1991-07-15
Buddy Hield      Sacramento Kings       SG 1992-12-17

In [244]:
nba.at["Austin Rivers", "Birthday"] # извлекаем конкретное значение через at, тк pandas оптимизирует алгоритмы под поиск отдельного значения (не проверяет тип входных данных, как lpc/iloc)

Timestamp('1992-08-01 00:00:00')

In [245]:
nba.iat[263, 1]

'PF'

In [246]:
%%timeit # проверяем время отработки кода
nba.at["Austin Rivers", "Birthday"]

7.61 µs ± 87.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [247]:
%%timeit
nba.loc["Austin Rivers", "Birthday"]

13.9 µs ± 2.84 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [248]:
%%timeit
nba.iat[263,1]

14.8 µs ± 3.27 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [249]:
%%timeit
nba.iloc[263,1]

20.1 µs ± 5.81 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

"""---4.8 ИЗВЛЕЧЕНИЕ ЗНАЧЕНИЙ ИЗ ОБЪЕКТОВ SERIES---"""

In [250]:
nba["Salary"].loc["Damian Lillard"]

np.int64(29802321)

In [251]:
nba["Salary"].at["Damian Lillard"]

np.int64(29802321)

In [252]:
nba["Salary"].iloc[234]

np.int64(2033160)

In [253]:
nba["Salary"].iat[234]

np.int64(2033160)

""---4.9 ПЕРЕИМЕНОВАНИЕ СТОЛБЦОВ И СТРОК---"""

In [254]:
nba.columns

Index(['Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [255]:
nba.columns = ["Team", "Position", "Date of Birth", "Pay"]
nba.head(1)

                            Team Position Date of Birth      Pay
Name
Shake Milton  Philadelphia 76ers       SG    1996-09-26  1445697

In [256]:
nba = nba.rename(columns={"Date of Birth" : "Birthday"})

In [257]:
nba.loc["Giannis Antetokounmpo"]

Team            Milwaukee Bucks
Position                     PF
Birthday    1994-12-06 00:00:00
Pay                    25842697
Name: Giannis Antetokounmpo, dtype: object

In [258]:
nba = nba.rename(index={"Giannis Antetokounmpo" : "Greek Freak"})

In [259]:
nba.loc["Greek Freak"]

Team            Milwaukee Bucks
Position                     PF
Birthday    1994-12-06 00:00:00
Pay                    25842697
Name: Greek Freak, dtype: object

""---4.10 ЗАМЕНА ИНДЕКСА---"""

In [260]:
nba.set_index("Team").head()

                   Position   Birthday      Pay
Team
Philadelphia 76ers       SG 1996-09-26  1445697
Detroit Pistons          PF 1995-09-27  1645357
Charlotte Hornets        PF 1998-08-23  3831840
Detroit Pistons          PG 1988-10-04  7317074
Philadelphia 76ers        G 1995-07-26    79568

In [261]:
nba.reset_index().head()

             Name                Team Position   Birthday      Pay
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [262]:
nba = nba.reset_index().set_index("Team")
nba

                               Name Position   Birthday       Pay
Team
Philadelphia 76ers     Shake Milton       SG 1996-09-26   1445697
Detroit Pistons      Christian Wood       PF 1995-09-27   1645357
Charlotte Hornets     PJ Washington       PF 1998-08-23   3831840
Detroit Pistons        Derrick Rose       PG 1988-10-04   7317074
Philadelphia 76ers    Marial Shayok        G 1995-07-26     79568
...                             ...      ...        ...       ...
Houston Rockets       Austin Rivers       PG 1992-08-01   2174310
Sacramento Kings        Harry Giles       PF 1998-04-22   2578800
Milwaukee Bucks         Robin Lopez        C 1988-04-01   4767000
Cleveland Cavaliers   Collin Sexton       PG 1999-01-04   4764960
Phoenix Suns            Ricky Rubio       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [270]:
nfl = pd.read_csv("nfl.csv",
                  parse_dates=["Birthday"]
)

nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]

In [271]:
nfl_count = nfl.set_index("Name")

nfl_count

                                    Team Position   Birthday   Salary
Name
Tremon Smith         Philadelphia Eagles       RB 1996-07-20   570000
Shawn Williams        Cincinnati Bengals       SS 1991-05-13  3500000
Adam Butler         New England Patriots       DT 1994-04-12   645000
Derek Wolfe               Denver Broncos       DE 1990-02-24  8000000
Jake Ryan           Jacksonville Jaguars      OLB 1992-02-27  1000000
...                                  ...      ...        ...      ...
Bashaud Breeland      Kansas City Chiefs       CB 1992-01-30   805000
Craig James          Philadelphia Eagles       CB 1996-04-29   570000
Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
Chuma Edoga                New York Jets       OT 1997-05-25   495000
Tajae Sharpe            Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 4 columns]

In [272]:
nfl["Team"].value_counts()

Team
New York Jets           58
Washington Redskins     56
Kansas City Chiefs      56
New Orleans Saints      55
San Francisco 49Ers     55
Denver Broncos          54
Minnesota Vikings       54
Los Angeles Chargers    54
Atlanta Falcons         53
Dallas Cowboys          53
Seattle Seahawks        53
Detroit Lions           53
Buffalo Bills           53
Chicago Bears           53
Philadelphia Eagles     52
New York Giants         52
Los Angeles Rams        52
Houston Texans          52
Arizona Cardinals       51
Oakland Raiders         51
Cincinnati Bengals      51
Green Bay Packers       51
Jacksonville Jaguars    50
New England Patriots    49
Indianapolis Colts      49
Carolina Panthers       49
Cleveland Browns        49
Miami Dolphins          49
Baltimore Ravens        48
Tampa Bay Buccaneers    47
Pittsburgh Steelers     47
Tennessee Titans        46
Name: count, dtype: int64

In [273]:
nfl.sort_values("Salary", ascending=False).head(5)

                 Name                  Team Position   Birthday    Salary
180      Kirk Cousins     Minnesota Vikings       QB 1988-08-19  27500000
905    Marcus Mariota      Tennessee Titans       QB 1993-10-30  20922000
1623   Jameis Winston  Tampa Bay Buccaneers       QB 1994-01-06  20922000
1343       Derek Carr       Oakland Raiders       QB 1991-03-28  19900000
150   Jimmy Garoppolo   San Francisco 49Ers       QB 1991-11-02  17200000

In [274]:
nfl.sort_values(["Team", "Salary"], ascending= [True, False])

                    Name                 Team Position   Birthday    Salary
1577      Chandler Jones    Arizona Cardinals      OLB 1990-02-27  16500000
669     Patrick Peterson    Arizona Cardinals       CB 1990-07-11  11000000
1361    Larry Fitzgerald    Arizona Cardinals       WR 1983-08-31  11000000
1594       David Johnson    Arizona Cardinals       RB 1991-12-16   5700000
948          Justin Pugh    Arizona Cardinals        G 1990-08-15   5000000
...                  ...                  ...      ...        ...       ...
1109  Ross Pierschbacher  Washington Redskins        C 1995-05-05    495000
1325       Kelvin Harmon  Washington Redskins       WR 1996-12-15    495000
1344          Wes Martin  Washington Redskins        G 1996-05-09    495000
1345      Jimmy Moreland  Washington Redskins       CB 1995-08-26    495000
1509       Jeremy Reaves  Washington Redskins       SS 1996-08-29    495000

[1655 rows x 5 columns]

In [275]:
nfl = nfl.set_index("Team")

nfl.loc["New York Jets"].head()

                           Name Position   Birthday   Salary
Team
New York Jets   Bronson Kaufusi       DE 1991-07-06   645000
New York Jets    Darryl Roberts       CB 1990-11-26  1000000
New York Jets     Jordan Willis       DE 1995-05-02   754750
New York Jets  Quinnen Williams       DE 1997-12-21   495000
New York Jets        Sam Ficken        K 1992-12-14   495000

In [277]:
nfl.sort_values("Birthday", ascending=True).head(1)

                           Name Position   Birthday    Salary
Team
New England Patriots  Tom Brady       QB 1977-08-03  14000000