<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%201.%20%D0%97%D0%BD%D0%B0%D0%BA%D0%BE%D0%BC%D1%81%D1%82%D0%B2%D0%BE%20%D1%81%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%BE%D0%B9%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---Глава 1. ЗНАКОМСТВО С БИБЛИОТЕКОЙ PANDAS---"""

"""---1.3 ОБЗОР БИБЛИОТЕКИ PANDAS---"""

"""---1.3.2. Операции над объектами DataFrame---"""

In [ ]:
import pandas as pd

In [ ]:
movies = pd.read_csv('movies.csv', index_col='Title') # импорт данных

In [ ]:
movies.iloc[499] # извлекаем строку по индексу (числовой позиции)

Rank           500
Studio         Fox
Gross     $288.30
Year          2018
Name: Maze Runner: The Death Cure, dtype: object

In [ ]:
movies.loc['Forrest Gump'] # извлекаем строку по индексу (по метке индекса)

Rank            119
Studio    Paramount
Gross      $677.90
Year           1994
Name: Forrest Gump, dtype: object

In [ ]:
movies.sort_values(by='Year', ascending=False).head() # сортируем датафрэйм по одному признаку

                                   Rank           Studio       Gross  Year
Title
Avengers: Endgame                     1      Buena Vista  $2,796.30   2019
Shazam!                             340  Warner Brothers    $364.10   2019
John Wick: Chapter 3 - Parabellum   458        Lionsgate    $304.70   2019
Dumbo                               369      Buena Vista    $351.80   2019
Godzilla: King of the Monsters      315  Warner Brothers    $378.10   2019

In [ ]:
movies.sort_values(by=['Studio', 'Year']).head() # сортируем датафрэйм по нескольким признакам

                         Rank       Studio     Gross  Year
Title
The Blair Witch Project   588      Artisan  $248.60   1999
101 Dalmatians            708  Buena Vista  $215.90   1961
The Jungle Book           755  Buena Vista  $205.80   1967
Who Framed Roger Rabbit   410  Buena Vista  $329.80   1988
Dead Poets Society        636  Buena Vista  $235.90   1989

In [ ]:
movies.sort_index().head() # сортируем индексы

                  Rank           Studio     Gross  Year
Title
10,000 B.C.        536  Warner Brothers  $269.80   2008
101 Dalmatians     708      Buena Vista  $215.90   1961
101 Dalmatians     425      Buena Vista  $320.70   1996
2 Fast 2 Furious   632        Universal  $236.40   2003
2012                93             Sony  $769.70   2009

"""---1.3.3. Подсчет значений в Series---"""

In [ ]:
movies['Studio'].value_counts().head(10) # считаем количество значений в указанном столбце

Studio
Warner Brothers    132
Buena Vista        125
Fox                117
Universal          109
Sony                86
Paramount           76
Dreamworks          27
Lionsgate           21
New Line            16
MGM                 11
Name: count, dtype: int64

"""---1.3.4. Фильтрация столбца по одному или нескольким критериям---"""

In [ ]:
movies[movies["Studio"] == "Universal"] # фильтруем указанный столбец по условию

                                Rank     Studio   Gross  Year
Title
Jurassic World                     6  Universal  1671.7  2015
Furious 7                          8  Universal  1516.0  2015
Jurassic World: Fallen Kingdom    13  Universal  1309.5  2018
The Fate of the Furious           17  Universal  1236.0  2017
Minions                           19  Universal  1159.4  2015
...                              ...        ...     ...   ...
The Break-Up                     763  Universal   205.0  2006
Everest                          766  Universal   203.4  2015
Patch Adams                      772  Universal   202.3  1998
Kindergarten Cop                 775  Universal   202.0  1990
Straight Outta Compton           776  Universal   201.6  2015

[109 rows x 4 columns]

или

In [ ]:
released_by_universal = (movies["Studio"] == "Universal")
movies[released_by_universal].head()

                                Rank     Studio       Gross  Year
Title
Jurassic World                     6  Universal  $1,671.70   2015
Furious 7                          8  Universal  $1,516.00   2015
Jurassic World: Fallen Kingdom    13  Universal  $1,309.50   2018
The Fate of the Furious           17  Universal  $1,236.00   2017
Minions                           19  Universal  $1,159.40   2015

In [ ]:
released_by_universal = movies["Studio"] == "Universal"
released_in_2015 = movies["Year"] == 2015
movies[released_by_universal & released_in_2015] # фильтрация по нескольким признакам (и то и другое (&))

                        Rank     Studio       Gross  Year
Title
Jurassic World             6  Universal  $1,671.70   2015
Furious 7                  8  Universal  $1,516.00   2015
Minions                   19  Universal  $1,159.40   2015
Fifty Shades of Grey     165  Universal    $571.00   2015
Pitch Perfect 2          504  Universal    $287.50   2015
Ted 2                    702  Universal    $216.70   2015
Everest                  766  Universal    $203.40   2015
Straight Outta Compton   776  Universal    $201.60   2015

In [ ]:
released_by_universal = movies["Studio"] == "Universal"
released_in_2015 = movies["Year"] == 2015
movies[released_by_universal | released_in_2015] # фильтрация по нескольким признакам (или то или другое (|))

                                Rank       Studio       Gross  Year
Title
Star Wars: The Force Awakens       4  Buena Vista  $2,068.20   2015
Jurassic World                     6    Universal  $1,671.70   2015
Furious 7                          8    Universal  $1,516.00   2015
Avengers: Age of Ultron            9  Buena Vista  $1,405.40   2015
Jurassic World: Fallen Kingdom    13    Universal  $1,309.50   2018
...                              ...          ...         ...   ...
The Break-Up                     763    Universal    $205.00   2006
Everest                          766    Universal    $203.40   2015
Patch Adams                      772    Universal    $202.30   1998
Kindergarten Cop                 775    Universal    $202.00   1990
Straight Outta Compton           776    Universal    $201.60   2015

[140 rows x 4 columns]

In [ ]:
before_1975 = movies['Year'] < 1975
movies[before_1975]

                    Rank           Studio     Gross  Year
Title
The Exorcist         252  Warner Brothers  $441.30   1973
Gone with the Wind   288              MGM  $402.40   1939
Bambi                540              RKO  $267.40   1942
The Godfather        604        Paramount  $245.10   1972
101 Dalmatians       708      Buena Vista  $215.90   1961
The Jungle Book      755      Buena Vista  $205.80   1967

In [ ]:
mid_80 = movies['Year'].between(1983, 1986) # фильтрация в интервале
movies[mid_80]

                                      Rank     Studio     Gross  Year
Title
Return of the Jedi                     222        Fox  $475.10   1983
Back to the Future                     311  Universal  $381.10   1985
Top Gun                                357  Paramount  $356.80   1986
Indiana Jones and the Temple of Doom   403  Paramount  $333.10   1984
Crocodile Dundee                       413  Paramount  $328.20   1986
Beverly Hills Cop                      432  Paramount  $316.40   1984
Rocky IV                               467        MGM  $300.50   1985
Rambo: First Blood Part II             469    TriStar  $300.40   1985
Ghostbusters                           485   Columbia  $295.20   1984
Out of Africa                          662  Universal  $227.50   1985

In [ ]:
has_dark_in_title = movies.index.str.lower().str.contains("dark")
movies[has_dark_in_title]

                                Rank           Studio   Gross  Year
Title
Transformers: Dark of the Moon    23        Paramount  1123.8  2011
The Dark Knight Rises             27  Warner Brothers  1084.9  2012
The Dark Knight                   39  Warner Brothers  1004.9  2008
Thor: The Dark World             132      Buena Vista   644.6  2013
Star Trek Into Darkness          232        Paramount   467.4  2013
Fifty Shades Darker              309        Universal   381.5  2017
Dark Shadows                     600  Warner Brothers   245.5  2012
Dark Phoenix                     603              Fox   245.1  2019

"""---1.3.5. Группировка данных---"""

In [ ]:
movies["Gross"].str.replace("$", "", regex = False ).str.replace(",", "", regex = False) # меняем все вхождения "$" и "," пустыми строками.
# regex = False отвечает за то, что будет удален только этот указанный символ.

Title
Avengers: Endgame               2796.30
Avatar                          2789.70
Titanic                         2187.50
Star Wars: The Force Awakens    2068.20
Avengers: Infinity War          2048.40
                                  ...
Yogi Bear                        201.60
Garfield: The Movie              200.80
Cats & Dogs                      200.70
The Hunt for Red October         200.50
Valkyrie                         200.30
Name: Gross, Length: 782, dtype: object

In [ ]:
(
  movies["Gross"]
  .str.replace("$", "", regex = False) # меянем значение точечно
  .str.replace(",", "", regex = False) # меянем значение точечно
  .astype(float) # преобразуем текст в число
)

Title
Avengers: Endgame               2796.3
Avatar                          2789.7
Titanic                         2187.5
Star Wars: The Force Awakens    2068.2
Avengers: Infinity War          2048.4
                                 ...
Yogi Bear                        201.6
Garfield: The Movie              200.8
Cats & Dogs                      200.7
The Hunt for Red October         200.5
Valkyrie                         200.3
Name: Gross, Length: 782, dtype: float64

In [ ]:
# # перезаписываем формат столбца в исходный DataFrame
movies["Gross"] = (
  movies["Gross"]
  .str.replace("$", "", regex = False)
  .str.replace(",", "", regex = False)
  .astype(float)
)

In [ ]:
movies['Gross'].mean() # средние кассовые сборы всех фильмов

np.float64(439.0308184143222)

In [ ]:
studios = movies.groupby("Studio") # сумма всех фильмов в каждой студии

In [ ]:
studios["Gross"].count().head()

Studio
Artisan                     1
Buena Vista               125
CL                          1
China Film Corporation      1
Columbia                    5
Name: Gross, dtype: int64

In [ ]:
studios["Gross"].count().sort_values(ascending = False).head() # сортировка Series по убыванию

Studio
Warner Brothers    132
Buena Vista        125
Fox                117
Universal          109
Sony                86
Name: Gross, dtype: int64

In [ ]:
studios["Gross"].sum().head() # сумма по столбцу Gross

Studio
Artisan                     248.6
Buena Vista               73585.0
CL                          228.1
China Film Corporation      699.8
Columbia                   1276.6
Name: Gross, dtype: float64

In [ ]:
studios["Gross"].sum().sort_values(ascending = False).head() # сортировка от большего к меньшему

Studio
Buena Vista        73585.0
Warner Brothers    58643.8
Fox                50420.8
Universal          44302.3
Sony               32822.5
Name: Gross, dtype: float64