<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%203.%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0%20Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---3. МЕТОДЫ КЛАССА SERIES---"""

"""---3.1 ИМПОРТ НАБОРА ДАННЫХ С ПОМОЩЬЮ ФУНКЦИИ READ_CSV---"""

In [1]:
import pandas as pd

In [2]:
pd.read_csv("pokemon.csv")

         Pokemon            Type
0      Bulbasaur  Grass / Poison
1        Ivysaur  Grass / Poison
2       Venusaur  Grass / Poison
3     Charmander            Fire
4     Charmeleon            Fire
..           ...             ...
804    Stakataka    Rock / Steel
805  Blacephalon    Fire / Ghost
806      Zeraora        Electric
807       Meltan           Steel
808     Melmetal           Steel

[809 rows x 2 columns]

In [3]:
pokemon = pd.read_csv("pokemon.csv", index_col="Pokemon")["Type"]
pokemon

Pokemon
Bulbasaur      Grass / Poison
Ivysaur        Grass / Poison
Venusaur       Grass / Poison
Charmander               Fire
Charmeleon               Fire
                    ...
Stakataka        Rock / Steel
Blacephalon      Fire / Ghost
Zeraora              Electric
Meltan                  Steel
Melmetal                Steel
Name: Type, Length: 809, dtype: object

In [4]:
pd.read_csv("google_stocks.csv", parse_dates=["Date"]).head()

        Date  Close
0 2004-08-19  49.98
1 2004-08-20  53.95
2 2004-08-23  54.50
3 2004-08-24  52.24
4 2004-08-25  52.80

In [5]:
google = pd.read_csv("google_stocks.csv",
                     parse_dates=["Date"],
                     index_col="Date"
)["Close"]
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [6]:
pd.read_csv("revolutionary_war.csv",
            index_col="Start Date",
            parse_dates=["Start Date"]
).tail()

                                Battle     State
Start Date
1782-09-11         Siege of Fort Henry  Virginia
1782-09-13  Grand Assault on Gibraltar       NaN
1782-10-18   Action of 18 October 1782       NaN
1782-12-06   Action of 6 December 1782       NaN
1783-01-22   Action of 22 January 1783  Virginia

In [7]:
pd.read_csv(
    "revolutionary_war.csv",
    index_col="Start Date",
    parse_dates=["Start Date"],
    usecols=["State", "Start Date"]
).tail()

               State
Start Date
1782-09-11  Virginia
1782-09-13       NaN
1782-10-18       NaN
1782-12-06       NaN
1783-01-22  Virginia

In [8]:
battles = pd.read_csv(
    "revolutionary_war.csv",
    index_col="Start Date", # задаем индекс
    parse_dates=["Start Date"], # преобразоваваем столбец "Start Date" в тип даты (datetime)
    usecols=["State", "Start Date"] # выбираем только нужные столбцы при чтении файла
)["State"]

"""---3.2 СОРТИРОВКА ОБЪЕКТОВ SERIES---"""

"""---3.2.1 Сортировка значений с помощью метода sort_values---"""

In [9]:
google.sort_values()

Date
2004-09-03      49.82
2004-09-01      49.94
2004-08-19      49.98
2004-09-02      50.57
2004-09-07      50.60
               ...
2019-04-23    1264.55
2019-10-25    1265.13
2018-07-26    1268.33
2019-04-26    1272.18
2019-04-29    1287.58
Name: Close, Length: 3824, dtype: float64

In [10]:
pokemon.sort_values()

Pokemon
Illumise                Bug
Silcoon                 Bug
Pinsir                  Bug
Burmy                   Bug
Wurmple                 Bug
                  ...
Tirtouga       Water / Rock
Relicanth      Water / Rock
Corsola        Water / Rock
Carracosta     Water / Rock
Empoleon      Water / Steel
Name: Type, Length: 809, dtype: object

In [11]:
pd.Series(data=["Adam", "adam", "Ben"]).sort_values() # сортируем в порядке возрастания (учитывая регистр)

0    Adam
2     Ben
1    adam
dtype: object

In [12]:
google.sort_values(ascending=False).head()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [13]:
pokemon.sort_values(ascending=False).head()

Pokemon
Empoleon      Water / Steel
Corsola        Water / Rock
Relicanth      Water / Rock
Carracosta     Water / Rock
Tirtouga       Water / Rock
Name: Type, dtype: object

In [14]:
battles.sort_values()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1782-08-08            NaN
1782-08-25            NaN
1782-09-13            NaN
1782-10-18            NaN
1782-12-06            NaN
Name: State, Length: 232, dtype: object

In [15]:
battles.sort_values(na_position="last") # явно располагаем nan в конце списка

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1782-08-08            NaN
1782-08-25            NaN
1782-09-13            NaN
1782-10-18            NaN
1782-12-06            NaN
Name: State, Length: 232, dtype: object

In [16]:
battles.sort_values(na_position="first") # явно располагаем nan в начале списка

Start Date
1775-09-17         NaN
1775-12-31         NaN
1776-03-03         NaN
1776-03-25         NaN
1776-05-18         NaN
                ...
1781-07-06    Virginia
1781-07-01    Virginia
1781-06-26    Virginia
1781-04-25    Virginia
1783-01-22    Virginia
Name: State, Length: 232, dtype: object

In [17]:
battles.dropna().sort_values() # удаляем из списка пустые значения (не по index)

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1781-07-06       Virginia
1781-07-01       Virginia
1781-06-26       Virginia
1781-04-25       Virginia
1783-01-22       Virginia
Name: State, Length: 162, dtype: object

"""---3.2.2 Сортировка по индексу с помощью метода sort_index---"""

In [18]:
pokemon.sort_index()

Pokemon
Abomasnow        Grass / Ice
Abra                 Psychic
Absol                   Dark
Accelgor                 Bug
Aegislash      Steel / Ghost
                  ...
Zoroark                 Dark
Zorua                   Dark
Zubat        Poison / Flying
Zweilous       Dark / Dragon
Zygarde      Dragon / Ground
Name: Type, Length: 809, dtype: object

In [19]:
battles.sort_index()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1783-01-22         Virginia
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
Name: State, Length: 232, dtype: object

In [20]:
battles.sort_index(na_position="first").head()

Start Date
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
1774-09-01    Massachusetts
Name: State, dtype: object

In [21]:
battles.sort_index(ascending=False).head()

Start Date
1783-01-22    Virginia
1782-12-06         NaN
1782-10-18         NaN
1782-09-13         NaN
1782-09-11    Virginia
Name: State, dtype: object

"""---3.2.3 Получение минимального и максимального значений с помощью методов nsmallest и nlargest---"""

In [27]:
google.sort_values(ascending=False).head()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [26]:
google.nlargest() # возвращаем максимальные значения из списка (по умолчанию n = 5)

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [25]:
google.nsmallest() # возвращаем минимальные значения из списка (по умолчанию n = 5)

Date
2004-09-03    49.82
2004-09-01    49.94
2004-08-19    49.98
2004-09-02    50.57
2004-09-07    50.60
Name: Close, dtype: float64

"""---3.4 ПОДСЧЕТ КОЛИЧЕСТВА ЗНАЧЕНИЙ С ПОМОЩЬЮ МЕТОДА VALUE_COUNTS---"""

In [30]:
pokemon.head()

Pokemon
Bulbasaur     Grass / Poison
Ivysaur       Grass / Poison
Venusaur      Grass / Poison
Charmander              Fire
Charmeleon              Fire
Name: Type, dtype: object

In [36]:
pokemon.value_counts()

Type
Normal              65
Water               61
Grass               38
Psychic             35
Fire                30
                    ..
Normal / Dragon      1
Psychic / Steel      1
Rock / Poison        1
Fighting / Ghost     1
Fire / Ghost         1
Name: count, Length: 159, dtype: int64

In [37]:
len(pokemon.value_counts()) # длина (количество) уникальных значений объекта Series

159

In [39]:
pokemon.nunique() # аналогия

159

In [41]:
pokemon.value_counts(ascending=True)

Type
Steel / Ground      1
Fire / Rock         1
Rock / Dark         1
Psychic / Grass     1
Fire / Steel        1
                   ..
Fire               30
Psychic            35
Grass              38
Water              61
Normal             65
Name: count, Length: 159, dtype: int64

In [43]:
pokemon.value_counts(normalize=True).head() # выводим соотношение количества частного к общему

Type
Normal     0.080346
Water      0.075402
Grass      0.046972
Psychic    0.043263
Fire       0.037083
Name: proportion, dtype: float64

In [48]:
pokemon.value_counts(normalize=True).head() * 100 # то же самое в %

Type
Normal     8.034611
Water      7.540173
Grass      4.697157
Psychic    4.326329
Fire       3.708282
Name: proportion, dtype: float64