<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%205.%20%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F%20%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2%20%D0%B2%20DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---5. ФИЛЬТРАЦИЯ ОБЪЕКТОВ DataFrame---"""

"""---5.1 ОПТИМИЗАЦИЯ ПАМЯТИ, ИСПОЛЬЗУЕМОЙ НАБОРОМ ДАННЫХ---"""

In [37]:
import pandas as pd

In [38]:
pd.read_csv("employees.csv")

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [39]:
employees = pd.read_csv("employees.csv", parse_dates = ["Start Date"])

employees

/tmp/ipykernel_8732/137010310.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv("employees.csv", parse_dates = ["Start Date"])

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [40]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

"""---5.1.1 Преобразование типов данных с помощью метода astype---"""

In [41]:
employees["Mgmt"].astype(bool) # создали объект Series. значение NaN преобразовалось в True.

0        True
1        True
2       False
3        True
4        True
        ...
996     False
997     False
998     False
999      True
1000     True
Name: Mgmt, Length: 1001, dtype: bool

In [42]:
employees["Mgmt"] = employees["Mgmt"].astype(bool) # это уже объект DataFrame

In [43]:
employees.tail()

     First Name Gender Start Date    Salary   Mgmt          Team
996     Phillip   Male 1984-01-31   42392.0  False       Finance
997     Russell   Male 2013-05-20   96914.0  False       Product
998       Larry   Male 2013-04-20   60500.0  False  Business Dev
999      Albert   Male 2012-05-15  129949.0   True         Sales
1000        NaN    NaN        NaT       NaN   True           NaN

In [44]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [45]:
employees["Salary"].fillna(0).astype(int).tail()

996      42392
997      96914
998      60500
999     129949
1000         0
Name: Salary, dtype: int64

In [46]:
employees["Salary"] = employees["Salary"].fillna(0).astype(int)

In [47]:
employees.nunique()

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [48]:
employees["Gender"].astype("category")

0         Male
1         Male
2       Female
3          NaN
4         Male
         ...
996       Male
997       Male
998       Male
999       Male
1000       NaN
Name: Gender, Length: 1001, dtype: category
Categories (2, object): ['Female', 'Male']

In [49]:
employees["Gender"] = employees["Gender"].astype("category")

In [50]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int64(1), object(2)
memory usage: 33.5+ KB

In [51]:
employees["Team"] = employees["Team"].astype("category")

In [52]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int64(1), object(1)
memory usage: 27.0+ KB

"""---5.2 ФИЛЬТРАЦИЯ ПО ОДНОМУ УСЛОВИЮ---"""

In [53]:
employees[employees["First Name"] == "Maria"] # извлекаем все записи True по условию

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [54]:
maries = employees["First Name"] == "Maria" # аналог строки выше

employees[maries]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [55]:
employees["Team"] != "Finance"

0        True
1        True
2       False
3       False
4        True
        ...
996     False
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [56]:
employees[employees["Team"] != "Finance"]

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
4         Larry    Male 1998-01-24  101004   True            IT
5        Dennis    Male 1987-04-18  115163  False         Legal
6          Ruby  Female 1987-08-17   65476   True       Product
...         ...     ...        ...     ...    ...           ...
995       Henry     NaN 2014-11-23  132483  False  Distribution
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[899 rows x 6 columns]

In [57]:
employees[employees["Mgmt"]].head() # так как столбец "Mgmt" уже булев, то нет смысла проверять его на условие. со старта в Pandas без явного указания будет True.

  First Name  Gender Start Date  Salary  Mgmt       Team
0    Douglas    Male 1993-08-06       0  True  Marketing
1     Thomas    Male 1996-03-31   61933  True        NaN
3      Jerry     NaN 2005-03-04  138705  True    Finance
4      Larry    Male 1998-01-24  101004  True         IT
6       Ruby  Female 1987-08-17   65476  True    Product

In [58]:
high_earners = employees["Salary"] > 100000
high_earners.head()

0    False
1    False
2     True
3     True
4     True
Name: Salary, dtype: bool

In [59]:
employees[high_earners].head()

  First Name  Gender Start Date  Salary   Mgmt          Team
2      Maria  Female        NaT  130590  False       Finance
3      Jerry     NaN 2005-03-04  138705   True       Finance
4      Larry    Male 1998-01-24  101004   True            IT
5     Dennis    Male 1987-04-18  115163  False         Legal
9    Frances  Female 2002-08-08  139852   True  Business Dev

"""---5.3 ФИЛЬТРАЦИЯ ПО НЕСКОЛЬКИМ УСЛОВИЯМ---"""

"""---5.3.1 Условие И---"""

In [60]:
is_female = employees["Gender"] == "Female"

In [61]:
in_biz_dev = employees["Team"] == "Business Dev"

In [62]:
employees[is_female & in_biz_dev].head() # & - оператор "И"

   First Name  Gender Start Date  Salary   Mgmt          Team
9     Frances  Female 2002-08-08  139852   True  Business Dev
33       Jean  Female 1993-12-18  119082  False  Business Dev
36     Rachel  Female 2009-02-16  142032  False  Business Dev
38  Stephanie  Female 1986-09-13   36844   True  Business Dev
61     Denise  Female 2001-11-06  106862  False  Business Dev

In [63]:
is_maneger = employees["Mgmt"]

employees[is_female & in_biz_dev & is_maneger].head()

    First Name  Gender Start Date  Salary  Mgmt          Team
9      Frances  Female 2002-08-08  139852  True  Business Dev
38   Stephanie  Female 1986-09-13   36844  True  Business Dev
66       Nancy  Female 2012-12-15  125250  True  Business Dev
92       Linda  Female 2000-05-25  119009  True  Business Dev
111     Bonnie  Female 1999-12-17   42153  True  Business Dev

"""---5.3.2 Условие ИЛИ---"""

In [64]:
earning_below_40k = employees["Salary"] < 40000
started_after_2015 = employees["Start Date"] > "2015-01-01"

In [65]:
employees[earning_below_40k | started_after_2015].tail() # | - оператор "ИЛИ"

     First Name  Gender Start Date  Salary   Mgmt         Team
958      Gloria  Female 1987-10-24   39833  False  Engineering
964       Bruce    Male 1980-05-07   35802   True        Sales
967      Thomas    Male 2016-03-12  105681  False  Engineering
989      Justin     NaN 1991-02-10   38344  False        Legal
1000        NaN     NaN        NaT       0   True          NaN

"""---5.3.3 Логистическое отрицание---"""

In [66]:
my_series = pd.Series([True, False, True])
my_series

0     True
1    False
2     True
dtype: bool

In [67]:
~my_series # меняет булев признак местами. False = True, True = False.

0    False
1     True
2    False
dtype: bool

In [68]:
employees[employees["Salary"] < 100000].head()

  First Name  Gender Start Date  Salary  Mgmt         Team
0    Douglas    Male 1993-08-06       0  True    Marketing
1     Thomas    Male 1996-03-31   61933  True          NaN
6       Ruby  Female 1987-08-17   65476  True      Product
7        NaN  Female 2015-07-20   45906  True      Finance
8     Angela  Female 2005-11-22   95570  True  Engineering

In [69]:
employees[~(employees["Salary"] > 100000)].head() # все, что после "~" нужно помещать в (), чтобы не нарушить послежовательность выполнения операции.

  First Name  Gender Start Date  Salary  Mgmt         Team
0    Douglas    Male 1993-08-06       0  True    Marketing
1     Thomas    Male 1996-03-31   61933  True          NaN
6       Ruby  Female 1987-08-17   65476  True      Product
7        NaN  Female 2015-07-20   45906  True      Finance
8     Angela  Female 2005-11-22   95570  True  Engineering

"""---5.4 ФИЛЬТРАЦИЯ ПО УСЛОВИЮ---"""

"""---5.4.1 Метод isin---"""

In [70]:
all_star_teams = ["Sales", "Legal", "Marketing"] # набор данных для поиска
on_all_star_teams = employees["Team"].isin(all_star_teams) # поиск объекта Series
employees[on_all_star_teams] # вывод поиска по DataFrame

    First Name  Gender Start Date  Salary   Mgmt       Team
0      Douglas    Male 1993-08-06       0   True  Marketing
5       Dennis    Male 1987-04-18  115163  False      Legal
11       Julie  Female 1997-10-26  102508   True      Legal
13        Gary    Male 2008-01-27  109831  False      Sales
20        Lois     NaN 1995-04-22   64714   True      Legal
..         ...     ...        ...     ...    ...        ...
986      Donna  Female 1982-11-26   82871  False  Marketing
989     Justin     NaN 1991-02-10   38344  False      Legal
991       Rose  Female 2002-08-25  134505   True  Marketing
994     George    Male 2013-06-21   98874   True  Marketing
999     Albert    Male 2012-05-15  129949   True      Sales

[280 rows x 6 columns]

"""---5.4.2 Метод between---"""

In [71]:
between_80k_and_90k = employees["Salary"].between(80000, 90000) # объект Series
employees[between_80k_and_90k].head() # применение объекта Series к DataFrame

   First Name  Gender Start Date  Salary   Mgmt         Team
19      Donna  Female 2010-07-22   81014  False      Product
31      Joyce     NaN 2005-02-20   88657  False      Product
35    Theresa  Female 2006-10-10   85182  False        Sales
45      Roger    Male 1980-04-17   88010   True        Sales
54       Sara  Female 2007-08-15   83677  False  Engineering

In [72]:
eighties_folk = employees["Start Date"].between("1980-01-01", "1990-01-01")
employees[eighties_folk].head()

   First Name  Gender Start Date  Salary   Mgmt     Team
5      Dennis    Male 1987-04-18  115163  False    Legal
6        Ruby  Female 1987-08-17   65476   True  Product
10     Louise  Female 1980-08-12   63241   True      NaN
12    Brandon    Male 1980-12-01  112807   True       HR
17      Shawn    Male 1986-12-07  111737  False  Product

In [73]:
name_starts_with_r = employees["First Name"].between("R", "S")
employees[name_starts_with_r].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
6        Ruby  Female 1987-08-17   65476   True       Product
36     Rachel  Female 2009-02-16  142032  False  Business Dev
45      Roger    Male 1980-04-17   88010   True         Sales
67     Rachel  Female 1999-08-16   51178   True       Finance
78      Robin  Female 1983-06-04  114797   True         Sales

"""---5.4.3 Методы isnull и notnull---"""

In [74]:
employees.head() # NaT - "не значение времени"

  First Name  Gender Start Date  Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       0   True  Marketing
1     Thomas    Male 1996-03-31   61933   True        NaN
2      Maria  Female        NaT  130590  False    Finance
3      Jerry     NaN 2005-03-04  138705   True    Finance
4      Larry    Male 1998-01-24  101004   True         IT

In [75]:
employees["Team"].isnull().head() # проверка на пустае значения

0    False
1     True
2    False
3    False
4    False
Name: Team, dtype: bool

In [76]:
employees["Start Date"].isnull().head()

0    False
1    False
2     True
3    False
4    False
Name: Start Date, dtype: bool

In [77]:
employees["Team"].notnull().head() # проверка на не пустые значения

0     True
1    False
2     True
3     True
4     True
Name: Team, dtype: bool

In [78]:
~(employees["Team"].isnull().head()) # обратная проверка на пустае значения (аналог "notnull")

0     True
1    False
2     True
3     True
4     True
Name: Team, dtype: bool

In [79]:
no_team = employees["Team"].isnull()

employees[no_team].head()

   First Name  Gender Start Date  Salary   Mgmt Team
1      Thomas    Male 1996-03-31   61933   True  NaN
10     Louise  Female 1980-08-12   63241   True  NaN
23        NaN    Male 2012-06-14  125792   True  NaN
32        NaN    Male 1998-08-21  122340   True  NaN
91      James     NaN 2005-01-26  128771  False  NaN

In [80]:
has_name = employees["First Name"].notnull()

employees[has_name].tail()

    First Name Gender Start Date  Salary   Mgmt          Team
995      Henry    NaN 2014-11-23  132483  False  Distribution
996    Phillip   Male 1984-01-31   42392  False       Finance
997    Russell   Male 2013-05-20   96914  False       Product
998      Larry   Male 2013-04-20   60500  False  Business Dev
999     Albert   Male 2012-05-15  129949   True         Sales

---5.4.4 Обработка пустых значений---

In [82]:
employees = pd.read_csv(
    "employees.csv",
    parse_dates=["Start Date"]
)

employees

/tmp/ipykernel_8732/2426245998.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv(

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [83]:
employees.dropna() # удаляем строки в которых есть минимум одно пропущенное значение

    First Name  Gender Start Date    Salary   Mgmt          Team
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
6         Ruby  Female 1987-08-17   65476.0   True       Product
8       Angela  Female 2005-11-22   95570.0   True   Engineering
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
994     George    Male 2013-06-21   98874.0   True     Marketing
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[761 rows x 6 columns]

In [84]:
employees.dropna(how="all").tail() # how = all - удаление строк, в которых все значения = пропущенные

    First Name Gender Start Date    Salary   Mgmt          Team
995      Henry    NaN 2014-11-23  132483.0  False  Distribution
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [85]:
employees.dropna(subset=["Gender"]).tail() # удаляем пустые значения из конкретного столбца

    First Name Gender Start Date    Salary   Mgmt          Team
994     George   Male 2013-06-21   98874.0   True     Marketing
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [86]:
employees.dropna(subset=["Start Date", "Salary"]).head() # удаляем пустые значения из нескольких указанных столбцов

  First Name  Gender Start Date    Salary   Mgmt     Team
1     Thomas    Male 1996-03-31   61933.0   True      NaN
3      Jerry     NaN 2005-03-04  138705.0   True  Finance
4      Larry    Male 1998-01-24  101004.0   True       IT
5     Dennis    Male 1987-04-18  115163.0  False    Legal
6       Ruby  Female 1987-08-17   65476.0   True  Product

In [87]:
employees.dropna(thresh=4).head() # удаляем строку, только если в ней меньше чем 4ре заполненых значения. Если заполненных ≥ 4 — строка остаётся.

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

"""---5.5 РЕШЕНИЕ ПРОБЛЕМ ДУБЛИКАТОВ---"""

"""---5.5.1 Метод duplicated---"""

In [88]:
employees["Team"].head()

0    Marketing
1          NaN
2      Finance
3      Finance
4           IT
Name: Team, dtype: object

In [89]:
employees["Team"].duplicated().head() # отмечаем первое вхождение дубликата как False, следующие как True

0    False
1    False
2    False
3     True
4    False
Name: Team, dtype: bool

In [90]:
employees["Team"].duplicated(keep="first").head() # keep - указывает, какое из дублирующих значений оставлять. first - первое из дубликата = не дубликат

0    False
1    False
2    False
3     True
4    False
Name: Team, dtype: bool

In [91]:
employees["Team"].duplicated(keep="last") # keep - указывает, какое из дублирующих значений оставлять. last - последнее вхождение = не дубликат

0        True
1        True
2        True
3        True
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [92]:
(~employees["Team"].duplicated()).head()

0     True
1     True
2     True
3    False
4     True
Name: Team, dtype: bool

In [93]:
first_one_in_team = ~employees["Team"].duplicated()

employees[first_one_in_team]

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

"""---5.5.2 Метод drop_duplicates---"""

In [94]:
employees.drop_duplicates(subset=["Team"]) # альтернатива предыдущему шагу. В данном случае True = первое вхождение (дубликат удаляется)

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

In [95]:
employees.drop_duplicates(subset=["Team"], keep="last") # в данном случае последние из дубликотов = True.

     First Name  Gender Start Date    Salary   Mgmt          Team
988       Alice  Female 2004-10-05   47638.0  False            HR
989      Justin     NaN 1991-02-10   38344.0  False         Legal
990       Robin  Female 1987-07-24  100765.0   True            IT
993        Tina  Female 1997-05-15   56450.0   True   Engineering
994      George    Male 2013-06-21   98874.0   True     Marketing
995       Henry     NaN 2014-11-23  132483.0  False  Distribution
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

In [96]:
employees.drop_duplicates(subset=["First Name"], keep=False) # оставляем только уникальные записи (не первое\последнее вхождение)

    First Name  Gender Start Date    Salary   Mgmt          Team
5       Dennis    Male 1987-04-18  115163.0  False         Legal
8       Angela  Female 2005-11-22   95570.0   True   Engineering
33        Jean  Female 1993-12-18  119082.0  False  Business Dev
190      Carol  Female 1996-03-19   57783.0  False       Finance
291      Tammy  Female 1984-11-11  132839.0   True            IT
495     Eugene    Male 1984-05-24   81077.0  False         Sales
688      Brian    Male 2007-04-07   93901.0   True         Legal
832      Keith    Male 2003-02-12  120672.0  False         Legal
887      David    Male 2009-12-05   92242.0  False         Legal

In [97]:
name_is_douglas = employees["First Name"] == "Douglas"
is_male = employees["Gender"] == "Male"
employees[name_is_douglas & is_male]

    First Name Gender Start Date    Salary   Mgmt         Team
0      Douglas   Male 1993-08-06       NaN   True    Marketing
217    Douglas   Male 1999-09-03   83341.0   True           IT
322    Douglas   Male 2002-01-08   41428.0  False      Product
835    Douglas   Male 2007-08-04  132175.0  False  Engineering

In [98]:
employees.drop_duplicates(subset=["Gender", "Team"]).head() # проверка на совпадение по нескольким столбцам. True = первое вхождение

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

"""---5.6 УПРАЖНЕНИЯ---"""

In [99]:
films = pd.read_csv("netflix.csv")
films.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   object
 3   type        5837 non-null   object
dtypes: object(4)
memory usage: 182.5+ KB

In [100]:
films = pd.read_csv("netflix.csv",
                    parse_dates=["date_added"],
                    )

films

/tmp/ipykernel_8732/1568807090.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  films = pd.read_csv("netflix.csv",

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [101]:
films.nunique() # проверяем уникальные значения для применения "категория"

title         5780
director      3024
date_added    1092
type             2
dtype: int64

In [109]:
films["type"].astype("category")

0       TV Show
1         Movie
2       TV Show
3         Movie
4         Movie
         ...
5832      Movie
5833      Movie
5834      Movie
5835      Movie
5836    TV Show
Name: type, Length: 5837, dtype: category
Categories (2, object): ['Movie', 'TV Show']

In [114]:
films["type"] = films["type"].astype("category")

films

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [112]:
films.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [120]:
p2 = films["title"] == "Limitless"

films[p2]

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [124]:
p3_1 = films["director"] == "Robert Rodriguez"
p3_2 = films["type"] == "Movie"

films[p3_1 & p3_2]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

In [127]:
p4_1 = films["date_added"] == "2019-07-31"
p4_2 = films["director"] == "Robert Altman"

films[p4_1 | p4_2]

                                title       director date_added     type
611                            Popeye  Robert Altman 2019-11-24    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie

In [137]:
p5_name = ["Orson Welles", "Aditya Kripalani", "Sam Raimi"]

p5_in_name = films["director"].isin(p5_name)

films[p5_in_name]

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

In [141]:
p6 = films["date_added"].between("2019-05-01", "2019-06-01")

films[p6].head()

                   title      director date_added     type
29            Chopsticks  Sachin Yardi 2019-05-31    Movie
60        Away From Home           NaN 2019-05-08  TV Show
82   III Smoking Barrels    Sanjib Dey 2019-06-01    Movie
108            Jailbirds           NaN 2019-05-10  TV Show
124              Pegasus       Han Han 2019-05-31    Movie

In [144]:
films

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [154]:
p7 = films.dropna(subset=["director"])

p7.head()

                                title        director date_added   type
1                      A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                           Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                   Shrek the Musical     Jason Moore 2013-12-29  Movie
5                    Schubert In Love     Lars Büchel 2018-03-01  Movie
6  We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie

In [155]:
films

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [171]:
films["date_added"].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5832     True
5833     True
5834     True
5835     True
5836     True
Name: date_added, Length: 5837, dtype: bool

In [179]:
films.drop_duplicates(subset = ["date_added"], keep=False)

,title,director,date_added,type
4,Shrek the Musical,Jason Moore,2013-12-29,Movie
12,Without Gorky,Cosima Spender,2017-05-31,Movie
30,Anjelah Johnson: Not Fancy,Jay Karas,2015-10-02,Movie
38,One Last Thing,Tim Rouhana,2019-08-25,Movie
70,Marvel's Iron Man & Hulk: Heroes United,Leo Riley,2014-02-16,Movie
...,...,...,...,...
5748,Menorca,John Barnard,2017-08-27,Movie
5749,Green Room,Jeremy Saulnier,2018-11-12,Movie
5788,Chris Brown: Welcome to My Life,Andrew Sandler,2017-10-07,Movie
5789,A Very Murray Christmas,Sofia Coppola,2015-12-04,Movie
5812,Little Singham in London,Prakash Satam,2019-04-22,Movie