<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%202%20%D0%9E%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%20Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---2. ОБОЪЕКТ SERIES---"""

"""---2.1 ОБЗОР SERIES---"""

"""---2.1.3. Пользовательские индексы для Series---"""

In [1]:
import pandas as pd
import numpy as np

In [2]:
ice_cream_flavors = [
  "Chocolate",
  "Vanilla",
  "Strawberry",
  "Rum Raisin",
]

pd.Series(ice_cream_flavors) # создание объекта Series

0     Chocolate
1       Vanilla
2    Strawberry
3    Rum Raisin
dtype: object

In [3]:
days_of_week = ("Monday", "Wednesday", "Friday", "Saturday")

In [4]:
pd.Series(ice_cream_flavors, days_of_week)
pd.Series(data = ice_cream_flavors, index = days_of_week)

Monday        Chocolate
Wednesday       Vanilla
Friday       Strawberry
Saturday     Rum Raisin
dtype: object

In [5]:
bunch_of_bools = [True, False, False]
pd.Series(bunch_of_bools)

0     True
1    False
2    False
dtype: bool

In [6]:
stock_prices = [985.32, 950.44]
time_of_day = ["Open", "Close"]
pd.Series(data = stock_prices, index = time_of_day)

Open     985.32
Close    950.44
dtype: float64

In [7]:
lucky_numbers = [4, 8, 15, 16, 23, 42]
pd.Series(lucky_numbers)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [8]:
lucky_numbers = [4, 8, 15, 16, 23, 42]
pd.Series(lucky_numbers, dtype = "float") # принудительно меняем формат передаваемых данных

0     4.0
1     8.0
2    15.0
3    16.0
4    23.0
5    42.0
dtype: float64

"""---2.1.4. Создание объекта Series
с пропущенными значениями---""

In [9]:
temperatures = [94, 88, np.nan, 91] # создаем пропущенное значение в объекте Series
pd.Series(temperatures)

0    94.0
1    88.0
2     NaN
3    91.0
dtype: float64

"""---2.2 СОЗДАНИЕ ОБЪЕКТОВ SERIES НА ОСНОВЕ ОБЪЕКТА ЯЗЫКА PYTHON---"""

In [10]:
# ассоциативный массив (словарь) (ключ: значение)
calorie_info = {
  "Cereal": 125,
  "Chocolate Bar": 406,
  "Ice Cream Sundae": 342,
}

diet = pd.Series(calorie_info)

diet

Cereal              125
Chocolate Bar       406
Ice Cream Sundae    342
dtype: int64

In [11]:
# кортежи
pd.Series(data = ("Red", "Green", "Blue")) # кортеж (неизменяемый список)

0      Red
1    Green
2     Blue
dtype: object

In [12]:
# кортежи в списке
rgb_colors = [(120, 41, 26), (196, 165, 45)] # кортежи, заключенные в список
pd.Series(data = rgb_colors)

0     (120, 41, 26)
1    (196, 165, 45)
dtype: object

In [13]:
# множество
my_set = {"Ricky", "Bobby"}
pd.Series(list(my_set)) # преобразуем множество в список (иначе будет ошибка)

0    Ricky
1    Bobby
dtype: object

In [14]:
# объект ndarray библиотеки NymPy
random_data = np.random.randint(1, 101, 10)
random_data

array([95, 89, 52, 60,  9, 15, 54, 43,  7, 15])

In [15]:
pd.Series(random_data) # передаем в Series объект ndarray

0    95
1    89
2    52
3    60
4     9
5    15
6    54
7    43
8     7
9    15
dtype: int64

"""---2.3 АТРИБУТЫ SERIES---"""

In [16]:
diet = {
    'Cereal': 125,
    'Chocolate Bar': 406,
    'Ice Cream Sundae': 342,
}

In [17]:
np.array(diet.values()) # обращаемся к объекту ndarray, в котором храняться значения

array(dict_values([125, 406, 342]), dtype=object)

In [18]:
pd.Series(diet).index # обращаемся к Series для определения индекса

Index(['Cereal', 'Chocolate Bar', 'Ice Cream Sundae'], dtype='object')

In [19]:
pd.Series(diet).dtype # обращаемся к Series для определения типа данных

dtype('int64')

In [20]:
pd.Series(diet).size # обращаемся к Series для определения количества элементов

3

In [21]:
pd.Series(diet).shape # обращаемся к Series для определения формы данных

(3,)

In [22]:
pd.Series(diet).is_unique # обращаемся к Series для определения уникальности данных

True

In [23]:
pd.Series(data=[3, 2, 1]).is_monotonic_decreasing # обращаемся к Series для определения монотонности данных (убывание)

True

In [24]:
pd.Series(data=[1, 3, 2]).is_monotonic_increasing # обращаемся к Series для определения монотонности данных (возрастание)

False

"""---2.4 ВОЗВРЩЕНИЕ ПЕРВОЙ И ПОСЛЕДНЕЙ СТРОК---"""

In [25]:
values = range(0, 500, 5)
pd.Series(data=values)

0       0
1       5
2      10
3      15
4      20
     ...
95    475
96    480
97    485
98    490
99    495
Length: 100, dtype: int64

In [26]:
nums = pd.Series(data=values)

In [27]:
nums.head(3) # возвращаем первые 3 строки

0     0
1     5
2    10
dtype: int64

In [28]:
nums.tail(3) # возвращаем последние 3 строки

97    485
98    490
99    495
dtype: int64

"""---2.5 МАТЕМАТИЧЕСКИЕ ОПЕРАЦИИ---"""

"""---2.5.1. Статистические операции---"""

In [29]:
numbers = pd.Series([1, 2, 3, np.nan, 4, 5])
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [30]:
numbers.count() # подсчет непустых значений

np.int64(5)

In [31]:
numbers.sum() # сумма непустых значений

np.float64(15.0)

In [32]:
numbers.sum(skipna = False) # определение суммы значений с пропущенными значениями

np.float64(nan)

In [33]:
numbers.sum(min_count = 3) # определение суммы значений с минимальным количеством непустых значений

np.float64(15.0)

In [34]:
numbers.product() # перемнажаем все значения Series

np.float64(120.0)

In [35]:
numbers.product(min_count=3)

np.float64(120.0)

In [36]:
numbers.cumsum() # нарастающая сумма

0     1.0
1     3.0
2     6.0
3     NaN
4    10.0
5    15.0
dtype: float64

In [37]:
numbers.cumsum(skipna = False) # рассчет нарастающей суммы до первого пустого знаяниея

0    1.0
1    3.0
2    6.0
3    NaN
4    NaN
5    NaN
dtype: float64

In [38]:
numbers.pct_change() # подтягивает вместо nan последнее (предыдущее nan) допустимое значение (также можно через 'pad' или 'ffill')

/tmp/ipykernel_7275/2024929600.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change() # подтягивает вместо nan последнее (предыдущее nan) допустимое значение (также можно через 'pad' или 'ffill')

0         NaN
1    1.000000
2    0.500000
3    0.000000
4    0.333333
5    0.250000
dtype: float64

In [39]:
numbers.pct_change(fill_method="bfill") # подтягивает вместо nan следуюшее (первое после nan) допустимое значение (также можно через 'bfill' или 'backfill')

/tmp/ipykernel_7275/3584170859.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change(fill_method="bfill") # подтягивает вместо nan следуюшее (первое после nan) допустимое значение (также можно через 'bfill' или 'backfill')

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.000000
5    0.250000
dtype: float64

In [40]:
numbers.mean() # вывод среднего значения (nan не учитывается)

np.float64(3.0)

In [41]:
numbers.median() # вывод значения, распопложенного посередине в отсортированном списке значений Series (nan не учитывается)

3.0

In [42]:
numbers.std() # вывод стандартного отклонения (мера отклонения данных от среднего значения)

1.5811388300841898

In [43]:
numbers.max() # извлекаем максимальное значение

5.0

In [44]:
numbers.min() # извлекаем минимальное значение

1.0

In [45]:
animals = pd.Series(["koala", "aardvark", "zebra"])
animals

0       koala
1    aardvark
2       zebra
dtype: object

In [46]:
animals.max() # ближайшая к концу алфавита буква

'zebra'

In [47]:
animals.min() # ближайшая к началу алфавита буква

'aardvark'

In [48]:
numbers.describe() # вся сводная информация об объекте Series

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [52]:
numbers.sample(3) # извлекаем случайный набор значений из объекта Series

2    3.0
5    5.0
0    1.0
dtype: float64

In [75]:
authors = pd.Series(
  ["Hemingway", "Orwell", "Dostoevsky", "Fitzgerald", "Orwell"]
)
authors.unique() # получаем неповторяющиеся значения из объекта

array(['Hemingway', 'Orwell', 'Dostoevsky', 'Fitzgerald'], dtype=object)

In [54]:
authors.nunique() # возвращаем количество уникальных значений

4

"""---2.5.2. Арифметические операции---"""

In [55]:
s1 = pd.Series(data = [5, np.nan, 15], index = ["A", "B", "C"])
s1

A     5.0
B     NaN
C    15.0
dtype: float64

In [56]:
s1 + 3 # операция сложения

A     8.0
B     NaN
C    18.0
dtype: float64

In [59]:
s1.add(3) # аналог операция сложения

A     8.0
B     NaN
C    18.0
dtype: float64

In [60]:
s1 - 5 # операция вычитания
s1.sub(5) # аналог
s1.subtract(5) # аналог

A     0.0
B     NaN
C    10.0
dtype: float64

In [61]:
s1 * 2 # операция умножения
s1.mul(2) # аналог
s1.multiply(2) # аналог

A    10.0
B     NaN
C    30.0
dtype: float64

In [62]:
s1 / 2 # операция деления
s1.div(2) # аналог
s1.divide(2) # аналог

A    2.5
B    NaN
C    7.5
dtype: float64

In [63]:
s1 // 4 # целочисленное деление (округление вниз)
s1.floordiv(4) # аналог

A    1.0
B    NaN
C    3.0
dtype: float64

In [67]:
s1 % 3
s1.mod(3)

A    2.0
B    NaN
C    0.0
dtype: float64

"""---2.5.3. Транслирование---"""

In [69]:
s1 = pd.Series([1, 2, 3], index = ["A", "B", "C"])
s2 = pd.Series([4, 5, 6], index = ["A", "B", "C"])
s1 + s2

A    5
B    7
C    9
dtype: int64

In [71]:
s1 = pd.Series(data = [3, 6, np.nan, 12])
s2 = pd.Series(data = [2, 6, np.nan, 12])
s1 == s2 # проверяем два объекта на равенство

0    False
1     True
2    False
3     True
dtype: bool

In [73]:
s1 != s2 # проверяем два объекта на неравенство
s1.ne(s2) # аналог

0     True
1    False
2     True
3    False
dtype: bool

In [80]:
s1 = pd.Series(
  data = [5, 10, 15], index = ["A", "B", "C"]
)
s2 = pd.Series(
  data = [4, 8, 12, 14], index = ["B", "C", "D", "E"]
)
s1 + s2

A     NaN
B    14.0
C    23.0
D     NaN
E     NaN
dtype: float64