<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%203.%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0%20Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---3. МЕТОДЫ КЛАССА SERIES---"""

"""---3.1 ИМПОРТ НАБОРА ДАННЫХ С ПОМОЩЬЮ ФУНКЦИИ READ_CSV---"""

In [3]:
import pandas as pd

In [6]:
pd.read_csv("pokemon.csv")

         Pokemon            Type
0      Bulbasaur  Grass / Poison
1        Ivysaur  Grass / Poison
2       Venusaur  Grass / Poison
3     Charmander            Fire
4     Charmeleon            Fire
..           ...             ...
804    Stakataka    Rock / Steel
805  Blacephalon    Fire / Ghost
806      Zeraora        Electric
807       Meltan           Steel
808     Melmetal           Steel

[809 rows x 2 columns]

In [27]:
pokemon = pd.read_csv("pokemon.csv", index_col="Pokemon")["Type"]
pokemon

Pokemon
Bulbasaur      Grass / Poison
Ivysaur        Grass / Poison
Venusaur       Grass / Poison
Charmander               Fire
Charmeleon               Fire
                    ...
Stakataka        Rock / Steel
Blacephalon      Fire / Ghost
Zeraora              Electric
Meltan                  Steel
Melmetal                Steel
Name: Type, Length: 809, dtype: object

In [8]:
pd.read_csv("google_stocks.csv", parse_dates=["Date"]).head()

        Date  Close
0 2004-08-19  49.98
1 2004-08-20  53.95
2 2004-08-23  54.50
3 2004-08-24  52.24
4 2004-08-25  52.80

In [28]:
google = pd.read_csv("google_stocks.csv",
                     parse_dates=["Date"],
                     index_col="Date"
)["Close"]
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [15]:
pd.read_csv("revolutionary_war.csv",
            index_col="Start Date",
            parse_dates=["Start Date"]
).tail()

                                Battle     State
Start Date
1782-09-11         Siege of Fort Henry  Virginia
1782-09-13  Grand Assault on Gibraltar       NaN
1782-10-18   Action of 18 October 1782       NaN
1782-12-06   Action of 6 December 1782       NaN
1783-01-22   Action of 22 January 1783  Virginia

In [16]:
pd.read_csv(
    "revolutionary_war.csv",
    index_col="Start Date",
    parse_dates=["Start Date"],
    usecols=["State", "Start Date"]
).tail()

               State
Start Date
1782-09-11  Virginia
1782-09-13       NaN
1782-10-18       NaN
1782-12-06       NaN
1783-01-22  Virginia

In [26]:
battles = pd.read_csv(
    "revolutionary_war.csv",
    index_col="Start Date",
    parse_dates=["Start Date"],
    usecols=["State", "Start Date"]
)["State"].tail()

"""---3.2 СОРТИРОВКА ОБЪЕКТОВ SERIES---"""

"""---3.2.1 Сортировка значений с помощью метода sort_values---"""

In [29]:
google.sort_values()

Date
2004-09-03      49.82
2004-09-01      49.94
2004-08-19      49.98
2004-09-02      50.57
2004-09-07      50.60
               ...
2019-04-23    1264.55
2019-10-25    1265.13
2018-07-26    1268.33
2019-04-26    1272.18
2019-04-29    1287.58
Name: Close, Length: 3824, dtype: float64

In [30]:
pokemon.sort_values()

Pokemon
Illumise                Bug
Silcoon                 Bug
Pinsir                  Bug
Burmy                   Bug
Wurmple                 Bug
                  ...
Tirtouga       Water / Rock
Relicanth      Water / Rock
Corsola        Water / Rock
Carracosta     Water / Rock
Empoleon      Water / Steel
Name: Type, Length: 809, dtype: object

In [31]:
pd.Series(data=["Adam", "adam", "Ben"]).sort_values()

0    Adam
2     Ben
1    adam
dtype: object

In [32]:
google.sort_values(ascending=False)

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
               ...
2004-09-07      50.60
2004-09-02      50.57
2004-08-19      49.98
2004-09-01      49.94
2004-09-03      49.82
Name: Close, Length: 3824, dtype: float64