<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%203.%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0%20Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---3. МЕТОДЫ КЛАССА SERIES---"""

"""---3.1 ИМПОРТ НАБОРА ДАННЫХ С ПОМОЩЬЮ ФУНКЦИИ READ_CSV---"""

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv("pokemon.csv")

         Pokemon            Type
0      Bulbasaur  Grass / Poison
1        Ivysaur  Grass / Poison
2       Venusaur  Grass / Poison
3     Charmander            Fire
4     Charmeleon            Fire
..           ...             ...
804    Stakataka    Rock / Steel
805  Blacephalon    Fire / Ghost
806      Zeraora        Electric
807       Meltan           Steel
808     Melmetal           Steel

[809 rows x 2 columns]

In [ ]:
pokemon = pd.read_csv("pokemon.csv", index_col="Pokemon")["Type"]
pokemon.info()

<class 'pandas.core.series.Series'>
Index: 809 entries, Bulbasaur to Melmetal
Series name: Type
Non-Null Count  Dtype
--------------  -----
809 non-null    object
dtypes: object(1)
memory usage: 12.6+ KB

In [ ]:
pd.read_csv("google_stocks.csv", parse_dates=["Date"]).head()

        Date  Close
0 2004-08-19  49.98
1 2004-08-20  53.95
2 2004-08-23  54.50
3 2004-08-24  52.24
4 2004-08-25  52.80

In [ ]:
google = pd.read_csv("google_stocks.csv",
                     parse_dates=["Date"],
                     index_col="Date"
)["Close"]
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [ ]:
pd.read_csv("revolutionary_war.csv",
            index_col="Start Date",
            parse_dates=["Start Date"]
).tail()

                                Battle     State
Start Date
1782-09-11         Siege of Fort Henry  Virginia
1782-09-13  Grand Assault on Gibraltar       NaN
1782-10-18   Action of 18 October 1782       NaN
1782-12-06   Action of 6 December 1782       NaN
1783-01-22   Action of 22 January 1783  Virginia

In [ ]:
pd.read_csv(
    "revolutionary_war.csv",
    index_col="Start Date",
    parse_dates=["Start Date"],
    usecols=["State", "Start Date"]
).tail()

               State
Start Date
1782-09-11  Virginia
1782-09-13       NaN
1782-10-18       NaN
1782-12-06       NaN
1783-01-22  Virginia

In [ ]:
battles = pd.read_csv(
    "revolutionary_war.csv",
    index_col="Start Date", # задаем индекс
    parse_dates=["Start Date"], # преобразоваваем столбец "Start Date" в тип даты (datetime)
    usecols=["State", "Start Date"] # выбираем только нужные столбцы при чтении файла
)["State"]

"""---3.2 СОРТИРОВКА ОБЪЕКТОВ SERIES---"""

"""---3.2.1 Сортировка значений с помощью метода sort_values---"""

In [ ]:
google.sort_values()

Date
2004-09-03      49.82
2004-09-01      49.94
2004-08-19      49.98
2004-09-02      50.57
2004-09-07      50.60
               ...
2019-04-23    1264.55
2019-10-25    1265.13
2018-07-26    1268.33
2019-04-26    1272.18
2019-04-29    1287.58
Name: Close, Length: 3824, dtype: float64

In [ ]:
pokemon.sort_values()

Pokemon
Illumise                Bug
Silcoon                 Bug
Pinsir                  Bug
Burmy                   Bug
Wurmple                 Bug
                  ...
Tirtouga       Water / Rock
Relicanth      Water / Rock
Corsola        Water / Rock
Carracosta     Water / Rock
Empoleon      Water / Steel
Name: Type, Length: 809, dtype: object

In [ ]:
pd.Series(data=["Adam", "adam", "Ben"]).sort_values() # сортируем в порядке возрастания (учитывая регистр)

0    Adam
2     Ben
1    adam
dtype: object

In [ ]:
google.sort_values(ascending=False).head()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [ ]:
pokemon.sort_values(ascending=False).head()

Pokemon
Empoleon      Water / Steel
Corsola        Water / Rock
Relicanth      Water / Rock
Carracosta     Water / Rock
Tirtouga       Water / Rock
Name: Type, dtype: object

In [ ]:
battles.sort_values()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1782-08-08            NaN
1782-08-25            NaN
1782-09-13            NaN
1782-10-18            NaN
1782-12-06            NaN
Name: State, Length: 232, dtype: object

In [ ]:
battles.sort_values(na_position="last") # явно располагаем nan в конце списка

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1782-08-08            NaN
1782-08-25            NaN
1782-09-13            NaN
1782-10-18            NaN
1782-12-06            NaN
Name: State, Length: 232, dtype: object

In [ ]:
battles.sort_values(na_position="first") # явно располагаем nan в начале списка

Start Date
1775-09-17         NaN
1775-12-31         NaN
1776-03-03         NaN
1776-03-25         NaN
1776-05-18         NaN
                ...
1781-07-06    Virginia
1781-07-01    Virginia
1781-06-26    Virginia
1781-04-25    Virginia
1783-01-22    Virginia
Name: State, Length: 232, dtype: object

In [ ]:
battles.dropna().sort_values() # удаляем из списка пустые значения (не по index)

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1781-07-06       Virginia
1781-07-01       Virginia
1781-06-26       Virginia
1781-04-25       Virginia
1783-01-22       Virginia
Name: State, Length: 162, dtype: object

"""---3.2.2 Сортировка по индексу с помощью метода sort_index---"""

In [ ]:
pokemon.sort_index()

Pokemon
Abomasnow        Grass / Ice
Abra                 Psychic
Absol                   Dark
Accelgor                 Bug
Aegislash      Steel / Ghost
                  ...
Zoroark                 Dark
Zorua                   Dark
Zubat        Poison / Flying
Zweilous       Dark / Dragon
Zygarde      Dragon / Ground
Name: Type, Length: 809, dtype: object

In [ ]:
battles.sort_index()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1783-01-22         Virginia
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
Name: State, Length: 232, dtype: object

In [ ]:
battles.sort_index(na_position="first").head()

Start Date
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
1774-09-01    Massachusetts
Name: State, dtype: object

In [ ]:
battles.sort_index(ascending=False).head()

Start Date
1783-01-22    Virginia
1782-12-06         NaN
1782-10-18         NaN
1782-09-13         NaN
1782-09-11    Virginia
Name: State, dtype: object

"""---3.2.3 Получение минимального и максимального значений с помощью методов nsmallest и nlargest---"""

In [ ]:
google.sort_values(ascending=False).head()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [ ]:
google.nlargest() # возвращаем максимальные значения из списка (по умолчанию n = 5)

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [ ]:
google.nsmallest() # возвращаем минимальные значения из списка (по умолчанию n = 5)

Date
2004-09-03    49.82
2004-09-01    49.94
2004-08-19    49.98
2004-09-02    50.57
2004-09-07    50.60
Name: Close, dtype: float64

"""---3.4 ПОДСЧЕТ КОЛИЧЕСТВА ЗНАЧЕНИЙ С ПОМОЩЬЮ МЕТОДА VALUE_COUNTS---"""

In [ ]:
pokemon.head()

Pokemon
Bulbasaur     Grass / Poison
Ivysaur       Grass / Poison
Venusaur      Grass / Poison
Charmander              Fire
Charmeleon              Fire
Name: Type, dtype: object

In [ ]:
pokemon.value_counts()

Type
Normal              65
Water               61
Grass               38
Psychic             35
Fire                30
                    ..
Normal / Dragon      1
Psychic / Steel      1
Rock / Poison        1
Fighting / Ghost     1
Fire / Ghost         1
Name: count, Length: 159, dtype: int64

In [ ]:
len(pokemon.value_counts()) # длина (количество) уникальных значений объекта Series

159

In [ ]:
pokemon.nunique() # аналогия

159

In [ ]:
pokemon.value_counts(ascending=True)

Type
Steel / Ground      1
Fire / Rock         1
Rock / Dark         1
Psychic / Grass     1
Fire / Steel        1
                   ..
Fire               30
Psychic            35
Grass              38
Water              61
Normal             65
Name: count, Length: 159, dtype: int64

In [ ]:
pokemon.value_counts(normalize=True).head() # выводим соотношение количества частного к общему

Type
Normal     0.080346
Water      0.075402
Grass      0.046972
Psychic    0.043263
Fire       0.037083
Name: proportion, dtype: float64

In [ ]:
pokemon.value_counts(normalize=True).head() * 100 # то же самое в %

Type
Normal     8.034611
Water      7.540173
Grass      4.697157
Psychic    4.326329
Fire       3.708282
Name: proportion, dtype: float64

In [ ]:
(pokemon.value_counts(normalize=True) * 100).round(2) # округление до 2х знаков

Type
Normal              8.03
Water               7.54
Grass               4.70
Psychic             4.33
Fire                3.71
                    ...
Normal / Dragon     0.12
Psychic / Steel     0.12
Rock / Poison       0.12
Fighting / Ghost    0.12
Fire / Ghost        0.12
Name: proportion, Length: 159, dtype: float64

In [ ]:
google.value_counts()

Close
288.92    3
307.10    3
194.27    3
290.41    3
287.68    3
         ..
293.41    1
296.75    1
295.46    1
297.76    1
287.67    1
Name: count, Length: 3696, dtype: int64

In [ ]:
google.max()

1287.58

In [ ]:
google.min()

49.82

In [ ]:
google.max() - google.min()

1237.76

In [ ]:
buckets = [0, 200, 400, 600, 800, 1000, 1200, 1400] # задаем интервал вхождений (корзины)
google.value_counts(bins = buckets) # считаем количество вхождений значений акций в этих интервалах ("(" - не включая; "]" - включая)

(200.0, 400.0]      1568
(-0.001, 200.0]      595
(400.0, 600.0]       575
(1000.0, 1200.0]     406
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [ ]:
google.value_counts(bins = buckets).sort_index()

(-0.001, 200.0]      595
(200.0, 400.0]      1568
(400.0, 600.0]       575
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1000.0, 1200.0]     406
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [ ]:
google.value_counts(bins = buckets, sort = False) # аналогично предыдущему коду

(-0.001, 200.0]      595
(200.0, 400.0]      1568
(400.0, 600.0]       575
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1000.0, 1200.0]     406
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [ ]:
google.value_counts(bins=6, sort=False).sort_index(ascending=True)

(48.581, 256.113]      1204
(256.113, 462.407]     1104
(462.407, 668.7]        507
(668.7, 874.993]        380
(874.993, 1081.287]     292
(1081.287, 1287.58]     337
Name: count, dtype: int64

In [ ]:
battles.head()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
Name: State, dtype: object

In [ ]:
battles.value_counts()

State
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Massachusetts     11
Pennsylvania      10
North Carolina     9
Florida            8
Georgia            6
Vermont            3
Rhode Island       3
Connecticut        3
New Hampshire      1
Delaware           1
Indiana            1
Louisiana          1
Ohio               1
Name: count, dtype: int64

In [ ]:
battles.value_counts(dropna=False).head()

State
NaN               70
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Name: count, dtype: int64

In [ ]:
battles.index

DatetimeIndex(['1774-09-01', '1774-12-14', '1775-04-19', '1775-04-19',
               '1775-04-20', '1775-05-10', '1775-05-27', '1775-06-11',
               '1775-06-17', '1775-08-08',
               ...
               '1782-08-08', '1782-08-15', '1782-08-19', '1782-08-26',
               '1782-08-25', '1782-09-11', '1782-09-13', '1782-10-18',
               '1782-12-06', '1783-01-22'],
              dtype='datetime64[ns]', name='Start Date', length=232, freq=None)

In [ ]:
battles.index.value_counts()

Start Date
1775-04-19    2
1778-09-07    2
1777-08-22    2
1781-04-25    2
1781-09-13    2
             ..
1782-09-11    1
1782-09-13    1
1782-10-18    1
1782-12-06    1
1783-01-22    1
Name: count, Length: 217, dtype: int64

"""---3.5 ВЫЗОВ ФУНКЦИИ ДЛЯ КАЖДОГО ИЗ ЗНАЧЕНИЙ ОБЪЕКТА SERIES С ПОМОЩЬЮ МЕТОДА APPLY---"""

In [ ]:
funcs = [len, max, min]

In [ ]:
for current_func in funcs:
  print(current_func(google))

3824
1287.58
49.82

In [ ]:
google.apply(round) # округляем значения до целого числа

Date
2004-08-19      50
2004-08-20      54
2004-08-23      54
2004-08-24      52
2004-08-25      53
              ...
2019-10-21    1246
2019-10-22    1243
2019-10-23    1259
2019-10-24    1261
2019-10-25    1265
Name: Close, Length: 3824, dtype: int64

In [ ]:
def sindle_or_multi(x): # x - переменная (тип нашего покемона)
  if "/" in x:
    return "Multi"
  return "Single"

In [ ]:
pokemon.apply(sindle_or_multi)

Pokemon
Bulbasaur       Multi
Ivysaur         Multi
Venusaur        Multi
Charmander     Single
Charmeleon     Single
                ...
Stakataka       Multi
Blacephalon     Multi
Zeraora        Single
Meltan         Single
Melmetal       Single
Name: Type, Length: 809, dtype: object

In [ ]:
pokemon.apply(sindle_or_multi).value_counts()

Type
Multi     405
Single    404
Name: count, dtype: int64

""---3.6 УПРАЖНЕНИЕ---"""

In [ ]:
import datetime as dt
today = dt.datetime(2020, 12, 26)
today.strftime("%A")

'Saturday'

!!! МОЕ РЕШЕНИЕ !!!

In [ ]:
war = pd.read_csv("revolutionary_war.csv")
war

                                Battle  Start Date          State
0                         Powder Alarm    9/1/1774  Massachusetts
1    Storming of Fort William and Mary  12/14/1774  New Hampshire
2     Battles of Lexington and Concord   4/19/1775  Massachusetts
3                      Siege of Boston   4/19/1775  Massachusetts
4                   Gunpowder Incident   4/20/1775       Virginia
..                                 ...         ...            ...
227                Siege of Fort Henry   9/11/1782       Virginia
228         Grand Assault on Gibraltar   9/13/1782            NaN
229          Action of 18 October 1782  10/18/1782            NaN
230          Action of 6 December 1782   12/6/1782            NaN
231          Action of 22 January 1783   1/22/1783       Virginia

[232 rows x 3 columns]

In [ ]:
war = pd.read_csv("revolutionary_war.csv",
                  parse_dates=["Start Date"],
                  index_col="Start Date")["State"]

war

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1782-09-11         Virginia
1782-09-13              NaN
1782-10-18              NaN
1782-12-06              NaN
1783-01-22         Virginia
Name: State, Length: 232, dtype: object

In [ ]:
pd.Series(war.index.strftime("%A"), index=war.index).value_counts()

Start Date
Saturday     39
Friday       39
Wednesday    32
Thursday     31
Sunday       31
Tuesday      29
Monday       27
Name: count, dtype: int64

!!! РЕШЕНИЕ ПО КНИГЕ !!!

In [ ]:
pd.read_csv("revolutionary_war.csv").head()

                              Battle  Start Date          State
0                       Powder Alarm    9/1/1774  Massachusetts
1  Storming of Fort William and Mary  12/14/1774  New Hampshire
2   Battles of Lexington and Concord   4/19/1775  Massachusetts
3                    Siege of Boston   4/19/1775  Massachusetts
4                 Gunpowder Incident   4/20/1775       Virginia

In [ ]:
days_of_war = pd.read_csv(
  "revolutionary_war.csv",
  usecols=["Start Date", "Battle"],
  parse_dates = ["Start Date"],
  index_col="Battle"
)["Start Date"]

days_of_war.head()

Battle
Powder Alarm                        1774-09-01
Storming of Fort William and Mary   1774-12-14
Battles of Lexington and Concord    1775-04-19
Siege of Boston                     1775-04-19
Gunpowder Incident                  1775-04-20
Name: Start Date, dtype: datetime64[ns]

In [ ]:
def day_of_week(date):
  return date.strftime("%A")

In [ ]:
days_of_war.dropna().apply(day_of_week)

Battle
Powder Alarm                          Thursday
Storming of Fort William and Mary    Wednesday
Battles of Lexington and Concord     Wednesday
Siege of Boston                      Wednesday
Gunpowder Incident                    Thursday
                                       ...
Siege of Fort Henry                  Wednesday
Grand Assault on Gibraltar              Friday
Action of 18 October 1782               Friday
Action of 6 December 1782               Friday
Action of 22 January 1783            Wednesday
Name: Start Date, Length: 228, dtype: object

In [ ]:
days_of_war.dropna().apply(day_of_week).value_counts()

Start Date
Saturday     39
Friday       39
Wednesday    32
Thursday     31
Sunday       31
Tuesday      29
Monday       27
Name: count, dtype: int64